-- UPDATE preguntas.tema / preguntas.subtema (clasificacion tematica PIR)
-- Fuente: ingesta/temas_clasificacion/ (Fase 1 subagentes por convocatoria +
-- Fase 2 consolidacion manual de sinonimos + fusion de temas con <=3
-- preguntas hacia un tema padre, conservando el original como subtema).
-- Cobertura: 1025 preguntas, 58 temas finales, 95 con subtema.

BEGIN;

DO $$
DECLARE
  total_antes int;
  con_tema_antes int;
BEGIN
  SELECT COUNT(*) INTO total_antes FROM public.preguntas;
  SELECT COUNT(*) INTO con_tema_antes FROM public.preguntas WHERE tema IS NOT NULL;
  IF total_antes != 1025 THEN
    RAISE EXCEPTION 'Se esperaban 1025 preguntas en total, hay % -- abortando.', total_antes;
  END IF;
  IF con_tema_antes != 0 THEN
    RAISE EXCEPTION 'Ya hay % preguntas con tema asignado -- abortando para no pisar datos.', con_tema_antes;
  END IF;
END $$;

ALTER TABLE public.preguntas ADD COLUMN IF NOT EXISTS subtema text;

UPDATE public.preguntas AS p
SET tema = v.tema, subtema = v.subtema
FROM (VALUES
  (1, 'Psicología Básica - Percepción y Atención', NULL),
  (2, 'Psicología Básica - Procesos Cognitivos', NULL),
  (3, 'Psicología Social', NULL),
  (4, 'Psicología del Aprendizaje', NULL),
  (5, 'Psicología Básica - Memoria', NULL),
  (6, 'Psicología del Aprendizaje', NULL),
  (7, 'Psicología Básica - Procesos Cognitivos', NULL),
  (8, 'Psicobiología', NULL),
  (9, 'Psicobiología', NULL),
  (10, 'Psicobiología', NULL),
  (11, 'Psicobiología', NULL),
  (12, 'Psicobiología', NULL),
  (13, 'Psicobiología', NULL),
  (14, 'Psicobiología', NULL),
  (15, 'Psicobiología', NULL),
  (16, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (17, 'Psicología Social', NULL),
  (18, 'Psicología Social', NULL),
  (19, 'Psicología Social', NULL),
  (20, 'Psicología Social', NULL),
  (21, 'Psicología Social', NULL),
  (22, 'Psicología Social', NULL),
  (23, 'Psicología del Desarrollo', NULL),
  (24, 'Psicología del Desarrollo', NULL),
  (25, 'Psicología del Desarrollo', NULL),
  (26, 'Psicología del Desarrollo', NULL),
  (27, 'Psicología del Desarrollo', NULL),
  (28, 'Psicología del Desarrollo', NULL),
  (29, 'Estadística', NULL),
  (30, 'Estadística', NULL),
  (31, 'Estadística', NULL),
  (32, 'Estadística', NULL),
  (33, 'Psicometría', NULL),
  (34, 'Metodología de Investigación', NULL),
  (35, 'Psicología de la Personalidad', NULL),
  (36, 'Psicología de la Personalidad', NULL),
  (37, 'Psicología Social', NULL),
  (38, 'Psicología Básica - Motivación', NULL),
  (39, 'Psicología Básica - Motivación', NULL),
  (40, 'Evaluación de la Inteligencia', NULL),
  (41, 'Evaluación de la Inteligencia', NULL),
  (42, 'Evaluación de la Inteligencia', NULL),
  (43, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (44, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (45, 'Psicología de la Personalidad', NULL),
  (46, 'Evaluación Psicológica', NULL),
  (47, 'Evaluación Psicológica', NULL),
  (48, 'Psicología de la Personalidad', NULL),
  (49, 'Evaluación Psicológica', NULL),
  (50, 'Evaluación Psicológica Infantojuvenil', NULL),
  (51, 'Evaluación Psicológica - Observación Conductual', NULL),
  (52, 'Evaluación Psicológica', NULL),
  (53, 'Evaluación Psicológica', NULL),
  (54, 'Evaluación Psicológica', NULL),
  (55, 'Psicometría', NULL),
  (56, 'Evaluación Psicológica', NULL),
  (57, 'Evaluación Psicológica - Observación Conductual', NULL),
  (58, 'Evaluación Psicológica', 'Evaluación Psicológica - Narrativa'),
  (59, 'Evaluación de la Inteligencia', NULL),
  (60, 'Evaluación Psicológica', NULL),
  (61, 'Evaluación Psicológica', NULL),
  (62, 'Evaluación Psicológica', NULL),
  (63, 'Evaluación Psicológica', 'Evaluación Psicológica - Narrativa'),
  (64, 'Evaluación Psicológica', NULL),
  (65, 'Evaluación Psicológica', NULL),
  (66, 'Evaluación Psicológica', NULL),
  (67, 'Evaluación Psicológica', NULL),
  (68, 'Evaluación Psicológica', NULL),
  (69, 'Evaluación de la Inteligencia', NULL),
  (70, 'Evaluación Psicológica - Observación Conductual', NULL),
  (71, 'Evaluación Psicológica Infantojuvenil', NULL),
  (72, 'Evaluación Psicológica Infantojuvenil', NULL),
  (73, 'Evaluación Psicológica Infantojuvenil', NULL),
  (74, 'Evaluación Psicológica Infantojuvenil', NULL),
  (75, 'Evaluación Psicológica Infantojuvenil', NULL),
  (76, 'Evaluación Psicológica Infantojuvenil', NULL),
  (77, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (78, 'Psicología de la Salud', NULL),
  (79, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (80, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (81, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (82, 'Psicopatología General', NULL),
  (83, 'Psicopatología General', NULL),
  (84, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (85, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (86, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (87, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (88, 'Psicopatología General', NULL),
  (89, 'Psicopatología General', NULL),
  (90, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (91, 'Psicopatología General', NULL),
  (92, 'Psicopatología General', NULL),
  (93, 'Psicopatología General', NULL),
  (94, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (95, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (96, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (97, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (98, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (99, 'Psicopatología General', NULL),
  (100, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (101, 'Psicopatología General', NULL),
  (102, 'Psicopatología - Sexualidad y Género', NULL),
  (103, 'Psicobiología', NULL),
  (104, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (105, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (106, 'Psicopatología - Sexualidad y Género', NULL),
  (107, 'Psicopatología - Sexualidad y Género', NULL),
  (108, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (109, 'Psicopatología - Sexualidad y Género', NULL),
  (110, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (111, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (112, 'Psicopatología General', 'Psicopatología - Trastornos del Control de Impulsos'),
  (113, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (114, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (115, 'Psicopatología - Trastornos del Sueño', NULL),
  (116, 'Psicopatología - Trastornos del Sueño', NULL),
  (117, 'Psicopatología - Trastornos del Sueño', NULL),
  (118, 'Evaluación Psicológica', NULL),
  (119, 'Psicopatología - Sexualidad y Género', NULL),
  (120, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (121, 'Psicopatología Infantojuvenil', NULL),
  (122, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (123, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (124, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (125, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (126, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (127, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (128, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (129, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (130, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (131, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (132, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (133, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (134, 'Evaluación Psicológica', NULL),
  (135, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (136, 'Tratamientos Psicológicos - TEPT', NULL),
  (137, 'Tratamientos Psicológicos - TEPT', NULL),
  (138, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (139, 'Tratamientos Psicológicos - TEPT', NULL),
  (140, 'Tratamientos Psicológicos - Adicciones', NULL),
  (141, 'Tratamientos Psicológicos - Adicciones', NULL),
  (142, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (143, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (144, 'Tratamientos Psicológicos - Adicciones', NULL),
  (145, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (146, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (147, 'Tratamientos Psicológicos - TEPT', 'Tratamientos Psicológicos - Trastornos Disociativos'),
  (148, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (149, 'Psicoterapia - Modelos y Enfoques', NULL),
  (150, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (151, 'Psicoterapia - Modelos y Enfoques', NULL),
  (152, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (153, 'Psicoterapia - Modelos y Enfoques', NULL),
  (154, 'Psicoterapia - Modelos y Enfoques', NULL),
  (155, 'Psicoterapia - Modelos y Enfoques', NULL),
  (156, 'Psicoterapia - Modelos y Enfoques', NULL),
  (157, 'Psicología del Aprendizaje', NULL),
  (158, 'Psicología del Aprendizaje', NULL),
  (159, 'Psicología del Aprendizaje', NULL),
  (160, 'Tratamientos Psicológicos - TEPT', 'Tratamientos Psicológicos - Trastornos Disociativos'),
  (161, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (162, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (163, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (164, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (165, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (166, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (167, 'Tratamientos Psicológicos - Trastornos de la Personalidad', NULL),
  (168, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (169, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (170, 'Tratamientos Psicológicos - Trastornos de la Personalidad', NULL),
  (171, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (172, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (173, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (174, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (175, 'Psicopatología Infantojuvenil', NULL),
  (176, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (177, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (178, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (179, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (180, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (181, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (182, 'Psicopatología Infantojuvenil', NULL),
  (183, 'Psicopatología Infantojuvenil', NULL),
  (184, 'Psicopatología Infantojuvenil', NULL),
  (185, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (186, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (187, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (188, 'Psicopatología Infantojuvenil', NULL),
  (189, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (190, 'Psicología de la Salud', NULL),
  (191, 'Psicología de la Salud', NULL),
  (192, 'Psicología de la Salud', NULL),
  (193, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (194, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (195, 'Evaluación de la Inteligencia', NULL),
  (196, 'Evaluación Psicológica', NULL),
  (197, 'Tratamientos Psicológicos - Adicciones', NULL),
  (198, 'Evaluación Psicológica - Observación Conductual', NULL),
  (199, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (200, 'Metodología de Investigación', NULL),
  (201, 'Psicología Social', NULL),
  (202, 'Psicología Básica - Percepción y Atención', NULL),
  (203, 'Estadística', NULL),
  (204, 'Estadística', NULL),
  (205, 'Estadística', NULL),
  (206, 'Psicometría', NULL),
  (207, 'Estadística', NULL),
  (208, 'Estadística', NULL),
  (209, 'Estadística', NULL),
  (210, 'Psicología Básica - Procesos Cognitivos', 'Psicología del Lenguaje'),
  (211, 'Psicología Básica - Memoria', NULL),
  (212, 'Psicología Básica - Procesos Cognitivos', NULL),
  (213, 'Psicología Básica - Percepción y Atención', 'Psicofísica'),
  (214, 'Psicología Básica - Memoria', NULL),
  (215, 'Psicología Básica - Motivación', NULL),
  (216, 'Psicología Básica - Procesos Cognitivos', NULL),
  (217, 'Psicología del Desarrollo', NULL),
  (218, 'Psicología del Desarrollo', NULL),
  (219, 'Psicología del Desarrollo', NULL),
  (220, 'Psicología del Desarrollo', NULL),
  (221, 'Psicología del Desarrollo', NULL),
  (222, 'Psicología del Desarrollo', NULL),
  (223, 'Psicología del Desarrollo', NULL),
  (224, 'Psicología Básica - Emoción', NULL),
  (225, 'Psicología Básica - Emoción', NULL),
  (226, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (227, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (228, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (229, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (230, 'Psicopatología - Trastornos del neurodesarrollo', NULL),
  (231, 'Psicopatología - Trastornos del neurodesarrollo', NULL),
  (232, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (233, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (234, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (235, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (236, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (237, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (238, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (239, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (240, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (241, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (242, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (243, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (244, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (245, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (246, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (247, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (248, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (249, 'Psicopatología - Sexualidad y Género', NULL),
  (250, 'Psicopatología - Sexualidad y Género', NULL),
  (251, 'Psicopatología - Sexualidad y Género', NULL),
  (252, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (253, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (254, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (255, 'Neuropsicología', NULL),
  (256, 'Neuropsicología', NULL),
  (257, 'Neuropsicología', NULL),
  (258, 'Neuropsicología', NULL),
  (259, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (260, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (261, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (262, 'Psicopatología - Trastornos del neurodesarrollo', NULL),
  (263, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (264, 'Psicopatología - Trastornos Disociativos', NULL),
  (265, 'Psicopatología - Trastornos Disociativos', NULL),
  (266, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (267, 'Psicopatología - Trastornos del Sueño', NULL),
  (268, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (269, 'Psicopatología - Trastornos Disociativos', NULL),
  (270, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (271, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (272, 'Psicopatología - Trastornos Disociativos', NULL),
  (273, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (274, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (275, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (276, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (277, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (278, 'Psicopatología - Trastornos del neurodesarrollo', NULL),
  (279, 'Neuropsicología', NULL),
  (280, 'Neuropsicología', NULL),
  (281, 'Neuropsicología', NULL),
  (282, 'Neuropsicología', NULL),
  (283, 'Neuropsicología', NULL),
  (284, 'Neuropsicología', NULL),
  (285, 'Neuropsicología', NULL),
  (286, 'Neuropsicología', NULL),
  (287, 'Neuropsicología', NULL),
  (288, 'Psicología Social', NULL),
  (289, 'Psicología Social', NULL),
  (290, 'Psicología Social', NULL),
  (291, 'Psicología Social', NULL),
  (292, 'Psicología Social', NULL),
  (293, 'Psicología Social', NULL),
  (294, 'Psicología Social', NULL),
  (295, 'Psicología de la Salud', NULL),
  (296, 'Psicología Social', NULL),
  (297, 'Psicología de la Personalidad', NULL),
  (298, 'Psicología de la Inteligencia', NULL),
  (299, 'Psicología Social', NULL),
  (300, 'Psicología de la Inteligencia', NULL),
  (301, 'Psicología de la Personalidad', NULL),
  (302, 'Psicología de la Personalidad', NULL),
  (303, 'Psicología de la Inteligencia', NULL),
  (304, 'Psicología de la Inteligencia', NULL),
  (305, 'Psicología de la Personalidad', NULL),
  (306, 'Psicología de la Inteligencia', NULL),
  (307, 'Psicología de la Personalidad', NULL),
  (308, 'Psicología de la Personalidad', NULL),
  (309, 'Evaluación Psicológica', NULL),
  (310, 'Evaluación Psicológica', NULL),
  (311, 'Evaluación Psicológica', NULL),
  (312, 'Evaluación Psicológica', NULL),
  (313, 'Evaluación Psicológica', NULL),
  (314, 'Evaluación Psicológica', NULL),
  (315, 'Evaluación Psicológica', NULL),
  (316, 'Evaluación Psicológica', NULL),
  (317, 'Evaluación Psicológica', NULL),
  (318, 'Evaluación Psicológica', NULL),
  (319, 'Evaluación Psicológica', NULL),
  (320, 'Evaluación Psicológica', NULL),
  (321, 'Evaluación Psicológica', NULL),
  (322, 'Evaluación Psicológica', NULL),
  (323, 'Evaluación Psicológica', NULL),
  (324, 'Evaluación Psicológica', NULL),
  (325, 'Evaluación Psicológica', NULL),
  (326, 'Psicología de la Inteligencia', NULL),
  (327, 'Psicometría', NULL),
  (328, 'Evaluación Psicológica', NULL),
  (329, 'Evaluación Psicológica', NULL),
  (330, 'Evaluación Psicológica', NULL),
  (331, 'Evaluación Psicológica', NULL),
  (332, 'Evaluación Psicológica', NULL),
  (333, 'Evaluación Psicológica', NULL),
  (334, 'Evaluación Psicológica', NULL),
  (335, 'Evaluación Psicológica', NULL),
  (336, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastornos de Conducta'),
  (337, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastornos de Conducta'),
  (338, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (339, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastornos de Conducta'),
  (340, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (341, 'Evaluación Psicológica', NULL),
  (342, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (343, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Discapacidad intelectual'),
  (344, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Trastornos del lenguaje'),
  (345, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Trastornos de Conducta Infantojuvenil'),
  (346, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (347, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (348, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (349, 'Psicofarmacología', NULL),
  (350, 'Psicofarmacología', NULL),
  (351, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (352, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (353, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (354, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (355, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (356, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (357, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (358, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (359, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (360, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (361, 'Psicopatología - Trastornos del Sueño', NULL),
  (362, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (363, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (364, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (365, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (366, 'Tratamientos Psicológicos - Adicciones', NULL),
  (367, 'Tratamientos Psicológicos - Adicciones', NULL),
  (368, 'Tratamientos Psicológicos - Adicciones', NULL),
  (369, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (370, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (371, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (372, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (373, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (374, 'Tratamientos Psicológicos - TEPT', NULL),
  (375, 'Tratamientos Psicológicos - TEPT', NULL),
  (376, 'Tratamientos Psicológicos - TEPT', NULL),
  (377, 'Tratamientos Psicológicos - TEPT', NULL),
  (378, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (379, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (380, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (381, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (382, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (383, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (384, 'Terapia Familiar Sistémica', NULL),
  (385, 'Psicoterapia - Modelos y Enfoques', 'Psicoanálisis'),
  (386, 'Psicología de la Salud', 'Tratamientos Psicológicos - Dolor crónico'),
  (387, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (388, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (389, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (390, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia centrada en soluciones'),
  (391, 'Tratamientos Psicológicos - Trastornos de Ansiedad', 'Tratamientos Psicológicos - Trastornos emocionales (transdiagnóstico)'),
  (392, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (393, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (394, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (395, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (396, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (397, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (398, 'Psicología Social', NULL),
  (399, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (400, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (401, 'Neuropsicología', NULL),
  (402, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (403, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', 'Tratamientos Psicológicos - Trastorno Bipolar'),
  (404, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (405, 'Neuropsicología', NULL),
  (406, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (407, 'Psicología del Aprendizaje', NULL),
  (408, 'Psicología del Aprendizaje', NULL),
  (409, 'Psicología Social', NULL),
  (410, 'Psicología Básica - Emoción', NULL),
  (411, 'Psicología Básica - Percepción y Atención', NULL),
  (412, 'Psicología Básica - Procesos Cognitivos', 'Psicología del Lenguaje'),
  (413, 'Psicología Básica - Memoria', NULL),
  (414, 'Psicología Básica - Procesos Cognitivos', NULL),
  (415, 'Psicología Básica - Percepción y Atención', 'Psicología de la Atención'),
  (416, 'Metodología de Investigación', NULL),
  (417, 'Metodología de Investigación', NULL),
  (418, 'Metodología de Investigación', NULL),
  (419, 'Metodología de Investigación', NULL),
  (420, 'Metodología de Investigación', NULL),
  (421, 'Metodología de Investigación', NULL),
  (422, 'Metodología de Investigación', NULL),
  (423, 'Ética y Deontología Profesional', NULL),
  (424, 'Ética y Deontología Profesional', NULL),
  (425, 'Psicoterapia - Factores Comunes', NULL),
  (426, 'Evaluación Psicológica', NULL),
  (427, 'Evaluación Psicológica', NULL),
  (428, 'Evaluación Psicológica', NULL),
  (429, 'Psicología de la Personalidad', NULL),
  (430, 'Evaluación Psicológica', NULL),
  (431, 'Evaluación Psicológica', NULL),
  (432, 'Evaluación Psicológica', NULL),
  (433, 'Psicopatología Infantojuvenil', NULL),
  (434, 'Evaluación Psicológica', NULL),
  (435, 'Evaluación Psicológica', NULL),
  (436, 'Psicopatología Infantojuvenil', NULL),
  (437, 'Psicopatología Infantojuvenil', NULL),
  (438, 'Evaluación Psicológica', NULL),
  (439, 'Psicología del Desarrollo', NULL),
  (440, 'Psicología del Desarrollo', NULL),
  (441, 'Psicología del Desarrollo', NULL),
  (442, 'Psicología del Desarrollo', NULL),
  (443, 'Psicología del Desarrollo', NULL),
  (444, 'Psicología del Desarrollo', NULL),
  (445, 'Psicología del Desarrollo', NULL),
  (446, 'Psicología de la Personalidad', NULL),
  (447, 'Psicología de la Personalidad', NULL),
  (448, 'Psicología de la Personalidad', NULL),
  (449, 'Psicología Básica - Emoción', NULL),
  (450, 'Psicología de la Personalidad', NULL),
  (451, 'Psicología de la Personalidad', NULL),
  (452, 'Psicología de la Personalidad', NULL),
  (453, 'Psicología de la Inteligencia', NULL),
  (454, 'Psicología de la Inteligencia', NULL),
  (455, 'Psicología de la Personalidad', NULL),
  (456, 'Psicología Diferencial', NULL),
  (457, 'Psicología de la Personalidad', NULL),
  (458, 'Psicología de la Inteligencia', NULL),
  (459, 'Evaluación Psicológica', NULL),
  (460, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (461, 'Neuropsicología', NULL),
  (462, 'Neuropsicología', NULL),
  (463, 'Neuropsicología', NULL),
  (464, 'Psicobiología', NULL),
  (465, 'Psicobiología', NULL),
  (466, 'Psicobiología', NULL),
  (467, 'Psicofarmacología', NULL),
  (468, 'Psicoterapia - Factores Comunes', NULL),
  (469, 'Psicoterapia - Factores Comunes', NULL),
  (470, 'Neuropsicología', NULL),
  (471, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (472, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (473, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (474, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (475, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (476, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (477, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (478, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (479, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (480, 'Psicología Básica - Memoria', NULL),
  (481, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (482, 'Neuropsicología', NULL),
  (483, 'Neuropsicología', NULL),
  (484, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (485, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (486, 'Psicopatología Infantojuvenil', NULL),
  (487, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (488, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (489, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (490, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (491, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (492, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (493, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (494, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (495, 'Tratamientos Psicológicos - TEPT', NULL),
  (496, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (497, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (498, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (499, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (500, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (501, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (502, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (503, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (504, 'Conducta Suicida', NULL),
  (505, 'Conducta Suicida', NULL),
  (506, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (507, 'Psicología de la Salud', NULL),
  (508, 'Psicología de la Salud', NULL),
  (509, 'Entrevista Motivacional', NULL),
  (510, 'Psicología de la Salud', NULL),
  (511, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (512, 'Psicología de la Salud', NULL),
  (513, 'Psicología de la Salud', NULL),
  (514, 'Psicología de la Salud', NULL),
  (515, 'Psicología de la Salud', NULL),
  (516, 'Psicoterapia - Modelos y Enfoques', 'Psicoanálisis'),
  (517, 'Psicoterapia - Factores Comunes', NULL),
  (518, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (519, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (520, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (521, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (522, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (523, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (524, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (525, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (526, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (527, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (528, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (529, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (530, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (531, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (532, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (533, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (534, 'Psicoterapia - Factores Comunes', NULL),
  (535, 'Psicoterapia - Factores Comunes', NULL),
  (536, 'Psicoterapia - Factores Comunes', NULL),
  (537, 'Psicoterapia - Factores Comunes', NULL),
  (538, 'Psicoterapia - Factores Comunes', NULL),
  (539, 'Neuropsicología', NULL),
  (540, 'Neuropsicología', NULL),
  (541, 'Neuropsicología', NULL),
  (542, 'Psicopatología General', NULL),
  (543, 'Psicopatología General', NULL),
  (544, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (545, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (546, 'Psicopatología - Trastornos del Sueño', NULL),
  (547, 'Psicopatología - Trastornos del Sueño', NULL),
  (548, 'Psicopatología Infantojuvenil', NULL),
  (549, 'Psicopatología - Trastornos del Sueño', NULL),
  (550, 'Tratamientos Psicológicos - Trastornos Sexuales y de Género', NULL),
  (551, 'Psicoterapia - Factores Comunes', NULL),
  (552, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia de Esquemas'),
  (553, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (554, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (555, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (556, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (557, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (558, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (559, 'Psicoterapia - Factores Comunes', NULL),
  (560, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia Cognitivo-Conductual'),
  (561, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (562, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (563, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (564, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (565, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (566, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (567, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (568, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (569, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (570, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (571, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (572, 'Psicopatología Infantojuvenil', NULL),
  (573, 'Psicopatología Infantojuvenil', NULL),
  (574, 'Psicopatología Infantojuvenil', NULL),
  (575, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (576, 'Psicopatología Infantojuvenil', NULL),
  (577, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (578, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (579, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (580, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (581, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (582, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (583, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (584, 'Psicopatología Infantojuvenil', NULL),
  (585, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (586, 'Psicopatología Infantojuvenil', NULL),
  (587, 'Psicopatología Infantojuvenil', NULL),
  (588, 'Psicopatología Infantojuvenil', NULL),
  (589, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (590, 'Psicopatología Infantojuvenil', NULL),
  (591, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (592, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (593, 'Psicopatología Infantojuvenil', NULL),
  (594, 'Psicología Social', NULL),
  (595, 'Psicología Social', NULL),
  (596, 'Psicología Social', NULL),
  (597, 'Psicología Social', NULL),
  (598, 'Psicología Básica - Procesos Cognitivos', NULL),
  (599, 'Psicología Social', NULL),
  (600, 'Psicología Social', NULL),
  (601, 'Psicología Social', NULL),
  (602, 'Psicología Social', NULL),
  (603, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (604, 'Psicopatología General', 'Psicopatología - Trastornos del Control de Impulsos'),
  (605, 'Tratamientos Psicológicos - Terapias de Tercera Generación', NULL),
  (606, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (607, 'Entrevista Motivacional', NULL),
  (608, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (609, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (610, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (611, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (612, 'Psicopatología Infantojuvenil', NULL),
  (613, 'Psicología del Aprendizaje', NULL),
  (614, 'Psicología Básica - Procesos Cognitivos', 'Psicología Cognitiva'),
  (615, 'Psicología Básica - Emoción', NULL),
  (616, 'Psicología del Desarrollo', NULL),
  (617, 'Psicología Básica - Percepción y Atención', 'Psicología de la Atención'),
  (618, 'Psicología Básica - Percepción y Atención', 'Psicofísica'),
  (619, 'Psicología Básica - Memoria', NULL),
  (620, 'Ética y Deontología Profesional', NULL),
  (621, 'Ética y Deontología Profesional', NULL),
  (622, 'Ética y Deontología Profesional', NULL),
  (623, 'Psicología de la Salud', NULL),
  (624, 'Evaluación Psicológica', NULL),
  (625, 'Evaluación Psicológica', NULL),
  (626, 'Evaluación Psicológica', NULL),
  (627, 'Evaluación Psicológica', NULL),
  (628, 'Evaluación Psicológica', NULL),
  (629, 'Evaluación Psicológica', NULL),
  (630, 'Neuropsicología', NULL),
  (631, 'Evaluación Psicológica', NULL),
  (632, 'Evaluación Psicológica', NULL),
  (633, 'Evaluación Psicológica', NULL),
  (634, 'Evaluación Psicológica', NULL),
  (635, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia Cognitivo-Conductual'),
  (636, 'Evaluación Psicológica', NULL),
  (637, 'Evaluación Psicológica', NULL),
  (638, 'Evaluación Psicológica', NULL),
  (639, 'Evaluación Psicológica', NULL),
  (640, 'Psicopatología Infantojuvenil', NULL),
  (641, 'Evaluación Psicológica', NULL),
  (642, 'Evaluación Psicológica', NULL),
  (643, 'Psicopatología Infantojuvenil', NULL),
  (644, 'Evaluación Psicológica', NULL),
  (645, 'Evaluación Psicológica', NULL),
  (646, 'Evaluación Psicológica', NULL),
  (647, 'Psicología del Desarrollo', NULL),
  (648, 'Psicología del Desarrollo', NULL),
  (649, 'Psicología del Desarrollo', NULL),
  (650, 'Psicología del Desarrollo', NULL),
  (651, 'Psicología del Desarrollo', NULL),
  (652, 'Psicología del Desarrollo', NULL),
  (653, 'Psicología de la Salud', 'Psicología Positiva'),
  (654, 'Psicología de la Personalidad', NULL),
  (655, 'Psicología de la Personalidad', NULL),
  (656, 'Psicología Diferencial', NULL),
  (657, 'Psicología de la Personalidad', NULL),
  (658, 'Psicología de la Inteligencia', NULL),
  (659, 'Psicología de la Inteligencia', NULL),
  (660, 'Psicología de la Personalidad', NULL),
  (661, 'Psicología Básica - Motivación', NULL),
  (662, 'Psicología de la Salud', 'Psicología Positiva'),
  (663, 'Psicología de la Salud', 'Psicología del Estrés y Afrontamiento'),
  (664, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (665, 'Psicología Diferencial', NULL),
  (666, 'Psicología de la Inteligencia', NULL),
  (667, 'Psicología Diferencial', NULL),
  (668, 'Psicobiología', NULL),
  (669, 'Neuropsicología', NULL),
  (670, 'Neuropsicología', NULL),
  (671, 'Neuropsicología', NULL),
  (672, 'Neuropsicología', NULL),
  (673, 'Psicobiología', NULL),
  (674, 'Neuropsicología', NULL),
  (675, 'Neuropsicología', NULL),
  (676, 'Psicobiología', NULL),
  (677, 'Psicología Social', NULL),
  (678, 'Psicología Social', NULL),
  (679, 'Psicología Social', NULL),
  (680, 'Psicología Social', NULL),
  (681, 'Psicología Social', NULL),
  (682, 'Psicología Social', NULL),
  (683, 'Psicología Social', NULL),
  (684, 'Psicometría', NULL),
  (685, 'Psicometría', NULL),
  (686, 'Estadística', NULL),
  (687, 'Estadística', NULL),
  (688, 'Estadística', NULL),
  (689, 'Psicometría', NULL),
  (690, 'Psicoterapia - Modelos y Enfoques', NULL),
  (691, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (692, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (693, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (694, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia Cognitivo-Conductual'),
  (695, 'Psicoterapia - Modelos y Enfoques', 'Tratamientos Psicológicos - Terapia interpersonal'),
  (696, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (697, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (698, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (699, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (700, 'Terapia Familiar Sistémica', NULL),
  (701, 'Terapia Familiar Sistémica', NULL),
  (702, 'Entrevista Motivacional', NULL),
  (703, 'Terapia Familiar Sistémica', NULL),
  (704, 'Terapia Familiar Sistémica', NULL),
  (705, 'Psicoterapia - Modelos y Enfoques', NULL),
  (706, 'Psicoterapia - Modelos y Enfoques', NULL),
  (707, 'Psicoterapia - Modelos y Enfoques', NULL),
  (708, 'Tratamientos Psicológicos - Trastornos de la Personalidad', NULL),
  (709, 'Tratamientos Psicológicos - Trastornos de la Personalidad', NULL),
  (710, 'Tratamientos Psicológicos - Trastornos de la Personalidad', NULL),
  (711, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (712, 'Psicopatología General', 'Duelo'),
  (713, 'Psicología de la Salud', NULL),
  (714, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (715, 'Psicoterapia - Modelos y Enfoques', NULL),
  (716, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (717, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (718, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (719, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (720, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (721, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (722, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (723, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (724, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (725, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (726, 'Psicoterapia - Modelos y Enfoques', NULL),
  (727, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (728, 'Conducta Suicida', NULL),
  (729, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (730, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (731, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (732, 'Tratamientos Psicológicos - Adicciones', NULL),
  (733, 'Tratamientos Psicológicos - TEPT', NULL),
  (734, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (735, 'Tratamientos Psicológicos - TEPT', NULL),
  (736, 'Psicopatología General', NULL),
  (737, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (738, 'Neuropsicología', NULL),
  (739, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (740, 'Psicopatología General', 'Psicopatología - Trastornos emocionales transdiagnósticos'),
  (741, 'Psicopatología General', NULL),
  (742, 'Psicopatología General', NULL),
  (743, 'Psicopatología General', NULL),
  (744, 'Psicopatología General', NULL),
  (745, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (746, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', 'Tratamientos Psicológicos - Trastorno Bipolar'),
  (747, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (748, 'Entrevista Motivacional', NULL),
  (749, 'Psicoterapia - Factores Comunes', 'Tratamientos Psicológicos - Práctica basada en la evidencia'),
  (750, 'Psicopatología General', NULL),
  (751, 'Psicopatología General', NULL),
  (752, 'Psicopatología General', NULL),
  (753, 'Psicopatología General', NULL),
  (754, 'Neuropsicología', NULL),
  (755, 'Psicopatología General', NULL),
  (756, 'Psicopatología General', NULL),
  (757, 'Psicopatología General', NULL),
  (758, 'Psicopatología General', NULL),
  (759, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (760, 'Psicopatología General', NULL),
  (761, 'Psicofarmacología', NULL),
  (762, 'Psicopatología General', NULL),
  (763, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (764, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (765, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (766, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (767, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (768, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (769, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (770, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (771, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (772, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (773, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (774, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (775, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (776, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (777, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (778, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (779, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (780, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (781, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (782, 'Psicopatología Infantojuvenil', NULL),
  (783, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (784, 'Psicopatología General', 'Duelo'),
  (785, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (786, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (787, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (788, 'Psicopatología Infantojuvenil', NULL),
  (789, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (790, 'Psicopatología Infantojuvenil', NULL),
  (791, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (792, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (793, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (794, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (795, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (796, 'Psicopatología Infantojuvenil', NULL),
  (797, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (798, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (799, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (800, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (801, 'Psicopatología General', 'Duelo'),
  (802, 'Evaluación Psicológica', NULL),
  (803, 'Psicopatología Infantojuvenil', NULL),
  (804, 'Psicopatología Infantojuvenil', NULL),
  (805, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (806, 'Psicopatología Infantojuvenil', NULL),
  (807, 'Psicopatología Infantojuvenil', NULL),
  (808, 'Ética y Deontología Profesional', NULL),
  (809, 'Psicopatología Infantojuvenil', NULL),
  (810, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (811, 'Psicobiología', NULL),
  (812, 'Estadística', NULL),
  (813, 'Psicología de la Inteligencia', NULL),
  (814, 'Psicobiología', NULL),
  (815, 'Evaluación Psicológica', NULL),
  (816, 'Psicología del Desarrollo', NULL),
  (817, 'Psicopatología General', NULL),
  (818, 'Psicología Básica - Percepción y Atención', 'Psicofísica'),
  (819, 'Psicología del Aprendizaje', NULL),
  (820, 'Tratamientos Psicológicos Infantojuveniles', NULL),
  (821, 'Psicología Básica - Memoria', NULL),
  (822, 'Psicología Básica - Memoria', NULL),
  (823, 'Psicología Básica - Percepción y Atención', NULL),
  (824, 'Psicología Básica - Procesos Cognitivos', NULL),
  (825, 'Psicología Básica - Motivación', NULL),
  (826, 'Psicología del Aprendizaje', NULL),
  (827, 'Psicología Básica - Procesos Cognitivos', NULL),
  (828, 'Psicología Básica - Memoria', NULL),
  (829, 'Psicometría', NULL),
  (830, 'Psicometría', NULL),
  (831, 'Psicometría', NULL),
  (832, 'Metodología de Investigación', NULL),
  (833, 'Metodología de Investigación', NULL),
  (834, 'Metodología de Investigación', NULL),
  (835, 'Metodología de Investigación', NULL),
  (836, 'Ética y Deontología Profesional', NULL),
  (837, 'Ética y Deontología Profesional', NULL),
  (838, 'Ética y Deontología Profesional', NULL),
  (839, 'Evaluación Psicológica', NULL),
  (840, 'Evaluación Psicológica', NULL),
  (841, 'Evaluación Psicológica', NULL),
  (842, 'Evaluación Psicológica', NULL),
  (843, 'Evaluación Psicológica', NULL),
  (844, 'Evaluación Psicológica', NULL),
  (845, 'Evaluación Psicológica', NULL),
  (846, 'Evaluación Psicológica', NULL),
  (847, 'Evaluación Psicológica', NULL),
  (848, 'Evaluación Psicológica', NULL),
  (849, 'Evaluación Psicológica', NULL),
  (850, 'Evaluación Psicológica', NULL),
  (851, 'Evaluación Psicológica Infantojuvenil', NULL),
  (852, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Depresión'),
  (853, 'Evaluación Psicológica Infantojuvenil', NULL),
  (854, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - TEA'),
  (855, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - TDAH'),
  (856, 'Evaluación Psicológica Infantojuvenil', NULL),
  (857, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - TOC'),
  (858, 'Evaluación Psicológica Infantojuvenil', NULL),
  (859, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Lenguaje y Pensamiento'),
  (860, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Teoría de la Mente'),
  (861, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Desarrollo del Dibujo'),
  (862, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Adolescencia'),
  (863, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Apego'),
  (864, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Apego'),
  (865, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Desarrollo Cognitivo'),
  (866, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Comunicación Preverbal'),
  (867, 'Psicología Diferencial', NULL),
  (868, 'Psicología Diferencial', NULL),
  (869, 'Psicología Diferencial', NULL),
  (870, 'Psicología Diferencial', NULL),
  (871, 'Psicología Básica - Motivación', NULL),
  (872, 'Psicología de la Personalidad', NULL),
  (873, 'Psicología de la Personalidad', NULL),
  (874, 'Psicología Diferencial', NULL),
  (875, 'Psicología Básica - Motivación', NULL),
  (876, 'Psicología Básica - Motivación', NULL),
  (877, 'Psicología de la Personalidad', NULL),
  (878, 'Psicobiología', NULL),
  (879, 'Psicobiología', NULL),
  (880, 'Psicobiología', NULL),
  (881, 'Neuropsicología', 'Neuropsicología - Memoria'),
  (882, 'Psicobiología', NULL),
  (883, 'Psicobiología', NULL),
  (884, 'Neuropsicología', 'Neuropsicología - Lenguaje'),
  (885, 'Psicobiología', NULL),
  (886, 'Neuropsicología', 'Neuropsicología - Praxias'),
  (887, 'Neuropsicología', 'Neuropsicología - Evaluación'),
  (888, 'Psicobiología', NULL),
  (889, 'Neuropsicología', 'Neuropsicología - Memoria'),
  (890, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (891, 'Neuropsicología', 'Neuropsicología - Atención y Percepción'),
  (892, 'Neuropsicología', 'Neuropsicología - Lenguaje'),
  (893, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (894, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (895, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (896, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (897, 'Psicopatología General', 'Psicopatología - Lenguaje y Pensamiento'),
  (898, 'Psicopatología General', 'Psicopatología - Lenguaje y Pensamiento'),
  (899, 'Neuropsicología', 'Neuropsicología - Memoria'),
  (900, 'Psicopatología - Trastornos Disociativos', NULL),
  (901, 'Psicopatología - Trastornos Disociativos', NULL),
  (902, 'Psicopatología - Trastornos de la Conducta Alimentaria', 'Psicopatología - Trastornos de la Imagen Corporal'),
  (903, 'Psicopatología - TOC y Trastornos Relacionados', NULL),
  (904, 'Tratamientos Psicológicos - TOC y Trastornos Relacionados', NULL),
  (905, 'Psicología de la Salud', NULL),
  (906, 'Psicología de la Salud', NULL),
  (907, 'Psicología Básica - Emoción', NULL),
  (908, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (909, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (910, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (911, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (912, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (913, 'Psicopatología - Trastornos de la Conducta Alimentaria', NULL),
  (914, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (915, 'Psicopatología - Trastornos del Sueño', NULL),
  (916, 'Psicopatología - Trastornos del Sueño', NULL),
  (917, 'Psicopatología - Trastornos del Sueño', NULL),
  (918, 'Psicopatología - Trastornos del Sueño', NULL),
  (919, 'Conducta Suicida', NULL),
  (920, 'Conducta Suicida', NULL),
  (921, 'Conducta Suicida', NULL),
  (922, 'Psicopatología General', NULL),
  (923, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (924, 'Tratamientos Psicológicos - Adicciones', NULL),
  (925, 'Neuropsicología', 'Neuropsicología - Funciones Ejecutivas'),
  (926, 'Psicología de la Salud', NULL),
  (927, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (928, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (929, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (930, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (931, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (932, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (933, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', NULL),
  (934, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (935, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (936, 'Tratamientos Psicológicos - TEPT', NULL),
  (937, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (938, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (939, 'Psicopatología - Trastorno de Estrés Postraumático', NULL),
  (940, 'Psicopatología General', 'Psicopatología - Trastorno de Adaptación'),
  (941, 'Tratamientos Psicológicos - TEPT', NULL),
  (942, 'Tratamientos Psicológicos - TEPT', NULL),
  (943, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (944, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (945, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (946, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (947, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (948, 'Psicopatología - Trastornos del Estado de Ánimo', NULL),
  (949, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (950, 'Psicopatología - Psicosis y Trastornos Psicóticos', NULL),
  (951, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (952, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (953, 'Psicología de la Salud', NULL),
  (954, 'Psicología de la Salud', NULL),
  (955, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (956, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (957, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (958, 'Tratamientos Psicológicos - TEPT', 'Tratamientos Psicológicos - Trastornos Disociativos'),
  (959, 'Psicopatología - Trastornos Disociativos', NULL),
  (960, 'Tratamientos Psicológicos - Trastornos del Estado de Ánimo', 'Tratamientos Psicológicos - Trastorno Bipolar'),
  (961, 'Tratamientos Psicológicos - Psicosis y Esquizofrenia', NULL),
  (962, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (963, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (964, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (965, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (966, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (967, 'Psicopatología - Adicciones y Conductas Adictivas', NULL),
  (968, 'Psicopatología General', NULL),
  (969, 'Psicopatología - Trastornos de Ansiedad', NULL),
  (970, 'Tratamientos Psicológicos - Trastornos de Ansiedad', NULL),
  (971, 'Psicopatología - Trastornos de Síntomas Somáticos', NULL),
  (972, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (973, 'Tratamientos Psicológicos - Trastornos de Síntomas Somáticos', NULL),
  (974, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (975, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (976, 'Tratamientos Psicológicos - Trastorno Límite de la Personalidad', NULL),
  (977, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (978, 'Conducta Suicida', NULL),
  (979, 'Psicopatología - Trastornos de la Personalidad', NULL),
  (980, 'Psicopatología - Trastornos Disociativos', NULL),
  (981, 'Psicoterapia - Modelos y Enfoques', 'Psicoterapia - Intervención Temprana'),
  (982, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Trauma Infantojuvenil'),
  (983, 'Conducta Suicida', 'Conducta Suicida Infantojuvenil'),
  (984, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - TEA'),
  (985, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - TDAH Infantil'),
  (986, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Ansiedad Infantojuvenil'),
  (987, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Ansiedad Infantojuvenil'),
  (988, 'Conducta Suicida', 'Conducta Suicida Infantojuvenil'),
  (989, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastorno del Lenguaje'),
  (990, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Ansiedad Generalizada'),
  (991, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Apego'),
  (992, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Depresión'),
  (993, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Depresión Infantojuvenil'),
  (994, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Encopresis'),
  (995, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Encopresis'),
  (996, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Discapacidad Intelectual'),
  (997, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Esquizofrenia'),
  (998, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastorno de la Comunicación Social'),
  (999, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastorno Negativista Desafiante'),
  (1000, 'Tratamientos Psicológicos Infantojuveniles', 'Tratamientos Psicológicos - Trastornos de Conducta Infantojuvenil'),
  (1001, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastorno Negativista Desafiante'),
  (1002, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (1003, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Apego Reactivo'),
  (1004, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Trastorno Negativista Desafiante'),
  (1005, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Consumo de Sustancias'),
  (1006, 'Conducta Suicida', 'Conducta Suicida Infantojuvenil'),
  (1007, 'Psicopatología Infantojuvenil', 'Psicopatología Infantojuvenil - Consumo de Sustancias'),
  (1008, 'Psicología Social', NULL),
  (1009, 'Psicología Social', NULL),
  (1010, 'Psicología Social', NULL),
  (1011, 'Psicología Básica - Memoria', NULL),
  (1012, 'Psicología Social', NULL),
  (1013, 'Psicología Social', NULL),
  (1014, 'Psicología Social', NULL),
  (1015, 'Psicología Social', NULL),
  (1016, 'Psicometría', NULL),
  (1017, 'Psicobiología', NULL),
  (1018, 'Psicopatología - Trastornos Neurocognitivos', NULL),
  (1019, 'Tratamientos Psicológicos - Trastornos de la Conducta Alimentaria', NULL),
  (1020, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Duelo Infantil'),
  (1021, 'Psicología del Aprendizaje', NULL),
  (1022, 'Evaluación Psicológica', NULL),
  (1023, 'Psicoterapia - Proceso y Relación Terapéutica', NULL),
  (1024, 'Psicología del Desarrollo', 'Psicología del Desarrollo - Desarrollo Moral'),
  (1025, 'Evaluación Psicológica Infantojuvenil', NULL)
) AS v(id, tema, subtema)
WHERE p.id = v.id;

DO $$
DECLARE
  total_despues int;
  sin_tema int;
  n_temas_despues int;
  n_subtema_despues int;
BEGIN
  SELECT COUNT(*) INTO total_despues FROM public.preguntas;
  SELECT COUNT(*) INTO sin_tema FROM public.preguntas WHERE tema IS NULL;
  SELECT COUNT(DISTINCT tema) INTO n_temas_despues FROM public.preguntas;
  SELECT COUNT(*) INTO n_subtema_despues FROM public.preguntas WHERE subtema IS NOT NULL;
  IF total_despues != 1025 THEN
    RAISE EXCEPTION 'Total de preguntas cambio: % -- abortando.', total_despues;
  END IF;
  IF sin_tema != 0 THEN
    RAISE EXCEPTION '% preguntas se quedaron sin tema -- abortando.', sin_tema;
  END IF;
  IF n_temas_despues != 58 THEN
    RAISE EXCEPTION 'Se esperaban 58 temas unicos, hay % -- abortando.', n_temas_despues;
  END IF;
  IF n_subtema_despues != 95 THEN
    RAISE EXCEPTION 'Se esperaban 95 filas con subtema, hay % -- abortando.', n_subtema_despues;
  END IF;
  RAISE NOTICE 'OK: % preguntas, % temas unicos, % con subtema.', total_despues, n_temas_despues, n_subtema_despues;
END $$;

COMMIT;
