-- CREATE + INSERT tabla temas (navegacion publica SEO /temas)
-- Fuente: ingesta/intros_temas_generadas.json (66 registros)
-- Indice por los 66 subtemas finos (columna tema), agrupados visualmente
-- por las 11 areas generales en la UI de /temas -- sin columna area aqui,
-- se deriva con split_part(tema, ' - ', 1) igual que en preguntas.area.

BEGIN;

CREATE TABLE IF NOT EXISTS temas (
  slug TEXT PRIMARY KEY,
  tema TEXT NOT NULL,
  intro TEXT NOT NULL,
  num_preguntas INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
DECLARE
  total_antes int;
BEGIN
  SELECT COUNT(*) INTO total_antes FROM public.temas;
  IF total_antes != 0 THEN
    RAISE EXCEPTION 'La tabla temas ya tiene % filas -- abortando para no duplicar.', total_antes;
  END IF;
END $$;

INSERT INTO temas (slug, tema, intro, num_preguntas)
VALUES
  ('quimica-farmaceutica-relacion-estructura-actividad-y-diseno-de-farmacos', 'Química Farmacéutica - Relación Estructura-Actividad y Diseño de Fármacos', 'La sección de Química Farmacéutica - Relación Estructura-Actividad y Diseño de Fármacos cubre los principios que vinculan la conformación molecular con la potencia terapéutica, la selectividad y la farmacocinética, además de las estrategias de optimización de candidatos y la evaluación de su perfil de toxicidad. Este tema es esencial para el examen FIR, pues permite comprender cómo se generan y mejoran los fármacos, aspecto clave en la práctica farmacéutica. Disponemos de 49 preguntas reales de convocatorias oficiales anteriores para que puedas practicar y afianzar tus conocimientos.', 49),
  ('microbiologia-bacteriologia', 'Microbiología - Bacteriología', 'El tema de Microbiología - Bacteriología abarca el estudio de los microorganismos grampositivos y gramnegativos, sus características morfológicas, fisiológicas y la identificación de patógenos comunes en el ámbito farmacéutico, así como los principios de la microbiología clínica y la resistencia bacteriana. Su relevancia radica en la necesidad de comprender la microbiota y los agentes infecciosos para garantizar la calidad y seguridad de los productos farmacéuticos y la correcta aplicación de terapias antimicrobianas. En la plataforma FIR Turel disponemos de 42 preguntas oficiales de convocatorias anteriores, lo que permite practicar con material auténtico y actualizado.', 42),
  ('quimica-farmaceutica-espectroscopia-y-tecnicas-instrumentales', 'Química Farmacéutica - Espectroscopia y Técnicas Instrumentales', 'La sección de Química Farmacéutica - Espectroscopia y Técnicas Instrumentales cubre los principios y aplicaciones de las principales técnicas analíticas, como UV-Vis, IR, RMN y cromatografía, que son esenciales para la identificación y cuantificación de compuestos farmacéuticos. Este contenido es clave para el examen FIR, pues permite evaluar la capacidad de los aspirantes para interpretar datos espectroscópicos y seleccionar métodos adecuados en situaciones clínicas. Además, dispones de 35 preguntas oficiales de convocatorias anteriores que puedes usar para afianzar tus conocimientos y practicar la resolución de problemas reales.', 35),
  ('farmacologia-sistema-nervioso-central-y-psicofarmacos', 'Farmacología - Sistema Nervioso Central y Psicofármacos', 'El tema Farmacología - Sistema Nervioso Central y Psicofármacos abarca los principios de acción, farmacocinética y efectos de los fármacos que actúan sobre el SNC, así como los psicofármacos más relevantes para la práctica farmacéutica. Se incluyen mecanismos de acción, indicaciones, contraindicaciones y efectos secundarios, lo que resulta esencial para responder con precisión a las preguntas de la convocatoria. Además, dispones de 34 preguntas reales de convocatorias oficiales anteriores para practicar y afianzar tus conocimientos.', 34),
  ('fisiopatologia-neurologia-y-organos-de-los-sentidos', 'Fisiopatología - Neurología y Órganos de los Sentidos', 'El bloque de Fisiopatología - Neurología y Órganos de los Sentidos cubre los mecanismos patológicos que afectan el sistema nervioso central y periférico, así como las alteraciones en la visión, audición, gusto y olfato, con énfasis en procesos inflamatorios, neurodegenerativos y trastornos sensoriales. Su relevancia radica en que la farmacología de estos órganos exige un conocimiento profundo de la fisiología y la patología para elegir tratamientos adecuados. En la plataforma encontrarás 34 preguntas reales de convocatorias oficiales anteriores para afianzar la práctica.', 34),
  ('quimica-farmaceutica-volumetrias-electroanalisis-y-validacion-de-metodos-analiticos', 'Química Farmacéutica - Volumetrías, Electroanálisis y Validación de Métodos Analíticos', 'El tema de Química Farmacéutica - Volumetrías, Electroanálisis y Validación de Métodos Analíticos cubre los principios y procedimientos de las técnicas cuantitativas más utilizadas en la farmacia, desde titulación y análisis volumétrico hasta métodos electroquímicos y criterios de validación de ensayo. Su relevancia radica en que el examen exige dominio de la exactitud, precisión y reproducibilidad de los métodos, aspectos críticos para la calidad de los productos farmacéuticos. Disponemos de 34 preguntas oficiales de convocatorias anteriores que puedes usar para afianzar tus conocimientos y evaluar tu preparación.', 34),
  ('farmacologia-toxicologia-y-antidotos', 'Farmacología - Toxicología y Antídotos', 'El apartado de Farmacología - Toxicología y Antídotos cubre los principios de acción y efectos de sustancias tóxicas, la clasificación de los antídotos, los mecanismos de protección y las estrategias de intervención clínica. Este contenido es esencial para el examen FIR, pues exige conocer tanto la fisiopatología de las intoxicaciones como la farmacoterapia de emergencia. En la plataforma tienes acceso a 30 preguntas reales de convocatorias oficiales anteriores, lo que te permite entrenar con material auténtico y actualizado.', 30),
  ('farmacologia-antiinfecciosos-y-antivirales', 'Farmacología - Antiinfecciosos y Antivirales', 'El tema Farmacología - Antiinfecciosos y Antivirales abarca los principios de acción, indicaciones, dosis y efectos adversos de los fármacos que combaten infecciones bacterianas, fúngicas y virales, así como la resistencia y la farmacocinética de estos agentes. Su relevancia radica en que el examen FIR evalúa la capacidad de elegir el tratamiento adecuado y comprender la interacción entre medicamentos y microorganismos. En la plataforma tienes 28 preguntas reales de convocatorias oficiales anteriores, lo que te permite practicar con el mismo formato y nivel de dificultad que el examen.', 28),
  ('farmacologia-farmacodinamia-interacciones-y-principios-generales', 'Farmacología - Farmacodinamia, Interacciones y Principios Generales', 'La farmacología, con énfasis en farmacodinamia, interacciones y principios generales, cubre los mecanismos de acción de los fármacos, sus efectos terapéuticos y adversos, así como la forma en que se modifican entre sí y con el organismo. Este bloque es esencial para comprender la racionalidad de los tratamientos y la seguridad en la práctica farmacéutica. En la plataforma de FIR Turel dispones de 26 preguntas oficiales de convocatorias anteriores, lo que te permite evaluar y afianzar tus conocimientos con material auténtico.', 26),
  ('bioquimica-metabolismo-energetico-y-de-glucidos', 'Bioquímica - Metabolismo Energético y de Glúcidos', 'El tema Bioquímica - Metabolismo Energético y de Glúcidos cubre los procesos bioquímicos que regulan la producción y utilización de energía en el organismo, desde la glicólisis y el ciclo de Krebs hasta la glucogénesis y la gluconeogénesis, además de la regulación hormonal y la relación con enfermedades metabólicas. Su dominio es esencial para el examen FIR de Farmacia, pues permite comprender la farmacocinética y la farmacodinamia de fármacos que actúan sobre rutas metabólicas. En la plataforma FIR Turel dispones de 25 preguntas reales de convocatorias oficiales anteriores para practicar y consolidar tus conocimientos.', 25),
  ('quimica-farmaceutica-fundamentos-de-quimica-general-e-inorganica', 'Química Farmacéutica - Fundamentos de Química General e Inorgánica', 'La sección de Química Farmacéutica - Fundamentos de Química General e Inorgánica cubre los principios básicos de la química que sustentan la formulación y la estabilidad de los fármacos, incluyendo la estructura atómica, enlaces químicos, propiedades de los compuestos inorgánicos y su interacción con el medio biológico. Este bloque es esencial porque permite comprender la lógica detrás de la síntesis, la purificación y la caracterización de los medicamentos que se evaluarán en el examen FIR. Además, dispones de 24 preguntas reales de convocatorias oficiales anteriores para practicar y consolidar tus conocimientos.', 24),
  ('analisis-clinicos-hematimetria-morfologia-celular-y-proteinograma', 'Análisis Clínicos - Hematimetría, Morfología Celular y Proteinograma', 'El apartado de Análisis Clínicos - Hematimetría, Morfología Celular y Proteinograma cubre la interpretación de valores sanguíneos, la identificación de alteraciones celulares y la evaluación de proteínas plasmáticas, aspectos esenciales para la valoración de pacientes en el ámbito farmacéutico. Este bloque exige conocer parámetros de hemograma, índices eritrocitarios, leucocitos y plaquetas, así como la clasificación de anormalidades morfológicas y la interpretación de proteinogramas. La práctica con preguntas reales de convocatorias oficiales previas, disponibles en 23 ejemplos, permite afianzar la comprensión y afinar la capacidad de respuesta bajo condiciones de examen.', 23),
  ('quimica-farmaceutica-profarmacos-y-metabolismo-de-farmacos', 'Química Farmacéutica - Profármacos y Metabolismo de Fármacos', 'El apartado de Química Farmacéutica - Profármacos y Metabolismo de Fármacos cubre la estructura, síntesis y propiedades de los compuestos que se transforman en el organismo, así como los mecanismos de acción y la farmacocinética que influyen en su eficacia y seguridad. Este contenido es clave para comprender cómo los fármacos interactúan con el cuerpo y se modifican, lo que determina la dosificación y el perfil de efectos adversos. En la plataforma FIR Turel dispones de 23 preguntas reales de convocatorias oficiales anteriores, ideales para afianzar estos conceptos.', 23),
  ('farmacologia-sistema-endocrino-metabolico-y-renal', 'Farmacología - Sistema Endocrino, Metabólico y Renal', 'El tema “Farmacología - Sistema Endocrino, Metabólico y Renal” abarca los principios farmacológicos que afectan a las glándulas endocrinas, al metabolismo de carbohidratos, lípidos y proteínas, así como a la función renal y la excreción de fármacos. Se centra en mecanismos de acción, efectos terapéuticos y adversos, y la interacción entre fármacos y sistemas fisiológicos, lo que resulta esencial para comprender la prescripción segura y eficaz. Para afianzar el aprendizaje, existen 21 preguntas oficiales de convocatorias anteriores que puedes usar para practicar y evaluar tu dominio del contenido.', 21),
  ('bioquimica-replicacion-reparacion-del-adn-y-tecnicas-moleculares', 'Bioquímica - Replicación, Reparación del ADN y Técnicas Moleculares', 'El tema de Bioquímica - Replicación, Reparación del ADN y Técnicas Moleculares cubre los mecanismos celulares que garantizan la integridad genética, desde la síntesis de la doble hélice hasta la corrección de errores y la aplicación de PCR, secuenciación y otras herramientas de diagnóstico. Su relevancia radica en que el examen evalúa la comprensión de procesos esenciales para la farmacología y la investigación clínica. Puedes reforzar tus conocimientos con 20 preguntas reales de convocatorias oficiales anteriores, disponibles para practicar en la plataforma.', 20),
  ('farmacologia-inmunomoduladores-y-terapias-biologicas', 'Farmacología - Inmunomoduladores y Terapias Biológicas', 'El apartado de Farmacología - Inmunomoduladores y Terapias Biológicas cubre los fármacos que actúan modulando la respuesta inmunitaria, desde agentes antiinflamatorios hasta anticuerpos monoclonales y pequeñas moléculas dirigidas a citocinas y receptores. Se centra en su mecanismo de acción, indicaciones clínicas, efectos adversos y consideraciones de seguridad, aspectos clave para la práctica farmacéutica y la toma de decisiones terapéuticas. En la plataforma tienes acceso a 20 preguntas oficiales de convocatorias anteriores, lo que te permite repasar casos reales y afianzar tu dominio del tema.', 20),
  ('farmacologia-sistema-cardiovascular', 'Farmacología - Sistema Cardiovascular', 'El apartado de Farmacología - Sistema Cardiovascular abarca los principios farmacodinámicos y farmacocinéticos de los fármacos que actúan sobre el corazón y la circulación, así como las indicaciones, dosis y efectos adversos que se evalúan en el examen FIR. Este contenido es crucial porque permite comprender la lógica de tratamiento de las patologías cardiovasculares, una de las áreas con mayor peso en la prueba. En la plataforma de FIR Turel tienes a tu disposición 20 preguntas reales de convocatorias oficiales anteriores para practicar y afianzar tus conocimientos.', 20),
  ('fisiopatologia-cardiologia-y-circulacion', 'Fisiopatología - Cardiología y Circulación', 'El bloque de Fisiopatología - Cardiología y Circulación cubre los mecanismos patológicos que alteran la función cardíaca y el sistema vascular, desde la hipertensión y la insuficiencia cardíaca hasta la enfermedad arterial coronaria y la arritmia. Este contenido es esencial porque permite comprender la base de las pruebas de diagnóstico y tratamiento que se evalúan en el examen FIR de Farmacia. En la plataforma de FIR Turel tienes acceso a 20 preguntas oficiales de convocatorias anteriores, lo que facilita la práctica con material auténtico y actualizado.', 20),
  ('fisiopatologia-endocrinologia-metabolismo-y-reproduccion', 'Fisiopatología - Endocrinología, Metabolismo y Reproducción', 'El bloque de Fisiopatología - Endocrinología, Metabolismo y Reproducción cubre los procesos fisiológicos y patológicos que afectan el sistema endocrino, el metabolismo energético y la función reproductiva, incluyendo la regulación hormonal, las alteraciones metabólicas y las disfunciones reproductivas. Este contenido es esencial para comprender la base de los diagnósticos clínicos y la farmacoterapia que se evalúa en el examen FIR de Farmacia. Además, dispones de 20 preguntas reales de convocatorias oficiales anteriores que puedes usar para practicar y afianzar tus conocimientos.', 20),
  ('farmacocinetica-absorcion-biofarmacia-y-vias-de-administracion', 'Farmacocinética - Absorción, Biofarmacia y Vías de Administración', 'El tema Farmacocinética - Absorción, Biofarmacia y Vías de Administración cubre los procesos que determinan la disponibilidad de un fármaco en el organismo, desde su entrada hasta su distribución y eliminación, así como los factores que influyen en la eficacia de cada vía de administración. Es esencial para el examen FIR porque permite evaluar la capacidad de los candidatos para optimizar la dosificación y garantizar la seguridad y eficacia terapéutica. Puedes acceder a 18 preguntas reales de convocatorias oficiales anteriores para practicar y consolidar tus conocimientos.', 18),
  ('microbiologia-diagnostico-microbiologico-tecnicas-de-laboratorio', 'Microbiología - Diagnóstico microbiológico (técnicas de laboratorio)', 'El tema de Microbiología - Diagnóstico microbiológico (técnicas de laboratorio) abarca los métodos y procedimientos que se utilizan en el laboratorio para identificar microorganismos patógenos, desde la recolección y cultivo de muestras hasta la interpretación de resultados. Se centra en técnicas de cultivo, identificación biológica, pruebas de sensibilidad y detección de patógenos específicos, aspectos esenciales para la práctica farmacéutica y la atención al paciente. Además, dispone de 18 preguntas oficiales de convocatorias anteriores que pueden emplearse para afianzar la comprensión y la aplicación práctica de los contenidos.', 18),
  ('microbiologia-parasitologia', 'Microbiología - Parasitología', 'El apartado de Microbiología - Parasitología cubre la identificación, fisiología y epidemiología de los parásitos que afectan a la salud humana, así como los métodos de diagnóstico y las estrategias de control. Este contenido es esencial para el examen FIR, pues permite evaluar la capacidad de los candidatos para reconocer y manejar infecciones parasitarias comunes y emergentes. En la plataforma de FIR Turel dispones de 18 preguntas reales de convocatorias oficiales anteriores, lo que facilita la práctica y la familiarización con el estilo de la prueba.', 18),
  ('quimica-farmaceutica-fisicoquimica-de-farmacos', 'Química Farmacéutica - Fisicoquímica de Fármacos', 'El tema de Química Farmacéutica - Fisicoquímica de Fármacos cubre los principios que rigen la solubilidad, estabilidad, permeabilidad y la interacción de los principios activos con excipientes, aspectos esenciales para la formulación y control de calidad de los medicamentos. Este bloque permite comprender cómo las propiedades físicas y químicas influyen en la biodisponibilidad y la eficacia terapéutica, lo que resulta crucial para responder con precisión a las preguntas del examen FIR. En la plataforma dispones de 18 preguntas oficiales reales de convocatorias anteriores, ideales para afianzar el conocimiento y evaluar tu preparación.', 18),
  ('fisiopatologia-digestivo-y-hepatobiliar', 'Fisiopatología - Digestivo y Hepatobiliar', 'El tema de Fisiopatología - Digestivo y Hepatobiliar abarca los mecanismos patológicos que afectan al sistema gastrointestinal y al hígado, incluyendo la inflamación, la fibrosis, la disfunción de la vesícula biliar y las alteraciones en la secreción de bilis. Su estudio es esencial para comprender las bases de las enfermedades que suelen aparecer en la convocatoria, como la cirrosis, la hepatitis y las patologías pancreáticas. En la plataforma de FIR Turel dispones de 17 preguntas reales de convocatorias oficiales anteriores para practicar y consolidar tus conocimientos.', 17),
  ('fisiopatologia-hematologia-y-oncologia', 'Fisiopatología - Hematología y Oncología', 'El apartado de Fisiopatología - Hematología y Oncología cubre los mecanismos patológicos que subyacen a las alteraciones sanguíneas y los tumores, desde la génesis celular hasta la presentación clínica y las vías de diagnóstico. Este bloque es esencial para el examen FIR, pues permite a los candidatos comprender las bases que justifican las pruebas y tratamientos farmacológicos que se evalúan. En la plataforma dispones de 17 preguntas reales de convocatorias oficiales anteriores, ideales para afianzar tu dominio y medir tu preparación.', 17),
  ('bioquimica-metabolismo-de-lipidos', 'Bioquímica - Metabolismo de Lípidos', 'El tema Bioquímica - Metabolismo de Lípidos abarca los procesos de síntesis, degradación y transporte de ácidos grasos, triglicéridos y colesterol, así como la regulación de las vías de β‑oxidación y la formación de moléculas señalizadoras. Su dominio es esencial para comprender la fisiología y las patologías asociadas a las alteraciones lipídicas, que suelen aparecer en las pruebas de FIR. Disponemos de 16 preguntas oficiales de convocatorias previas que permiten practicar con material auténtico y verificar la comprensión de cada concepto clave.', 16),
  ('analisis-clinicos-bioquimica-metabolica-electrolitica-y-endocrina', 'Análisis Clínicos - Bioquímica Metabólica, Electrolítica y Endocrina', 'El análisis clínico abarca la bioquímica metabólica, la electrolítica y la endocrina, cubriendo desde la determinación de glucosa, ácidos grasos y lípidos, hasta la evaluación de electrolitos y hormonas clave como la tiroides y la adrenal. Este bloque es esencial para el examen FIR, pues permite valorar la función metabólica y el equilibrio homeostático, aspectos críticos en la práctica farmacéutica. Puedes reforzar tu preparación con 14 preguntas reales de convocatorias oficiales anteriores, disponibles para practicar y afianzar tus conocimientos.', 14),
  ('farmacocinetica-metabolismo-eliminacion-y-farmacogenetica', 'Farmacocinética - Metabolismo, Eliminación y Farmacogenética', 'El tema “Farmacocinética - Metabolismo, Eliminación y Farmacogenética” cubre los procesos que determinan la vida de los fármacos dentro del organismo, desde su absorción y distribución hasta su metabolismo hepático y excreción renal, además de la influencia de variantes genéticas en la respuesta individual. Comprender estos mecanismos es esencial para interpretar la dosificación, la eficacia y la seguridad de los medicamentos, aspectos clave en el examen FIR de Farmacia. En la plataforma FIR Turel dispones de 14 preguntas reales de convocatorias oficiales anteriores que te permitirán afianzar tus conocimientos y evaluar tu preparación.', 14),
  ('quimica-farmaceutica-sintesis-de-farmacos-y-rutas-de-obtencion', 'Química Farmacéutica - Síntesis de Fármacos y Rutas de Obtención', 'El tema “Química Farmacéutica - Síntesis de Fármacos y Rutas de Obtención” cubre los procesos químicos que transforman materias primas en compuestos farmacéuticos, desde la elección de reactivos y condiciones de reacción hasta la purificación y caracterización final. Su relevancia radica en que el examen exige comprender cómo se obtienen los principios activos y la lógica detrás de cada paso para garantizar calidad y eficacia. En la plataforma dispones de 14 preguntas reales de convocatorias oficiales anteriores, ideales para afianzar estos conceptos.', 14),
  ('tecnologia-farmaceutica-formas-solidas-polvos-y-operaciones-basicas', 'Tecnología Farmacéutica - Formas Sólidas, Polvos y Operaciones Básicas', 'El apartado de Tecnología Farmacéutica - Formas Sólidas, Polvos y Operaciones Básicas cubre los principios de formulación, procesamiento y control de calidad de productos farmacéuticos en estado sólido, así como las técnicas de manipulación de polvos y las operaciones básicas de fabricación. Se centra en la comprensión de la solubilidad, la estabilidad, la granulación y las normas GMP, aspectos clave para garantizar la eficacia y seguridad de los medicamentos. Los candidatos pueden reforzar su preparación con 14 preguntas reales de convocatorias oficiales anteriores, lo que permite evaluar el dominio de los conceptos y practicar la aplicación en situaciones de examen.', 14),
  ('farmacocinetica-modelos-y-cinetica-de-eliminacion', 'Farmacocinética - Modelos y Cinética de Eliminación', 'En el temario FIR, la sección “Farmacocinética - Modelos y Cinética de Eliminación” cubre los principios que rigen la absorción, distribución, metabolismo y excreción de fármacos, así como los modelos matemáticos que permiten predecir la concentración plasmática a lo largo del tiempo. Este apartado es esencial para comprender la eficacia y seguridad de los medicamentos, y se evalúa con preguntas que exigen aplicar conceptos de farmacocinética clínica y de laboratorio. Disponemos de 13 preguntas oficiales de convocatorias anteriores que puedes usar para afinar tu dominio de estos temas.', 13),
  ('farmacologia-oncologia-e-inmunoterapia-antineoplasica', 'Farmacología - Oncología e Inmunoterapia Antineoplásica', 'El apartado de Farmacología - Oncología e Inmunoterapia Antineoplásica cubre los fármacos de primera y segunda línea, mecanismos de acción, indicaciones, efectos secundarios y estrategias de combinación terapéutica, así como la farmacocinética y farmacodinamia de los agentes inmunoterapéuticos. Este contenido es clave para el examen FIR, pues exige comprender la lógica clínica y la evidencia que sustenta cada tratamiento antineoplásico. Para afianzar la práctica, existen 13 preguntas oficiales de convocatorias anteriores que puedes usar para evaluar tu dominio del tema.', 13),
  ('inmunologia-inmunidad-adaptativa-linfocitos-t-memoria-y-vacunacion', 'Inmunología - Inmunidad adaptativa: linfocitos T, memoria y vacunación', 'El apartado de inmunología que trata la inmunidad adaptativa se centra en el funcionamiento de los linfocitos T, la formación de memoria inmunológica y los principios que rigen la vacunación, aspectos clave para la práctica farmacéutica y la gestión de la salud pública. Se profundiza en la diferenciación de células T citotóxicas y auxiliares, la respuesta a antígenos y la importancia de la memoria celular para la protección a largo plazo. Además, existen 13 preguntas oficiales de convocatorias previas que puedes usar para afianzar tus conocimientos y evaluar tu preparación.', 13),
  ('legislacion-farmaceutica-autorizacion-y-registro-de-medicamentos', 'Legislación Farmacéutica - Autorización y Registro de Medicamentos', 'El tema “Legislación Farmacéutica - Autorización y Registro de Medicamentos” cubre los procedimientos legales y normativos que rigen la entrada de fármacos al mercado, desde la solicitud de autorización sanitaria hasta el registro y la supervisión post‑comercialización. Es esencial para el examen porque los candidatos deben demostrar conocimiento de los requisitos de calidad, seguridad y eficacia que deben cumplirse antes de que un producto pueda ser dispensado. Además, existen 13 preguntas oficiales de convocatorias anteriores que puedes usar para practicar y afianzar estos conceptos.', 13),
  ('quimica-farmaceutica-cromatografia-y-tecnicas-de-separacion', 'Química Farmacéutica - Cromatografía y Técnicas de Separación', 'La sección de Química Farmacéutica - Cromatografía y Técnicas de Separación cubre los principios y aplicaciones de los métodos de separación, desde la cromatografía en capa fina y de gases hasta la cromatografía líquida de alta resolución, además de la preparación de muestras y la interpretación de resultados. Este contenido es esencial para el examen FIR, pues permite evaluar la capacidad de identificar y controlar la pureza de los compuestos farmacéuticos. Puedes practicar con 13 preguntas oficiales reales de convocatorias anteriores, lo que facilita la familiarización con el estilo y la dificultad de los enunciados.', 13),
  ('quimica-farmaceutica-farmacognosia-y-productos-naturales', 'Química Farmacéutica - Farmacognosia y Productos Naturales', 'La química farmacéutica abarca la farmacognosia y los productos naturales, estudiando la composición, extracción y análisis de compuestos activos de origen vegetal y animal, así como su clasificación, propiedades farmacológicas y posibles interacciones. Este bloque es esencial para el examen FIR porque permite identificar y valorar las sustancias que pueden incorporarse a formulaciones farmacéuticas, garantizando su calidad y seguridad. En la plataforma de FIR Turel dispones de 12 preguntas reales de convocatorias oficiales anteriores para practicar y afianzar este conocimiento.', 12),
  ('bioquimica-genetica-molecular-mutaciones-y-regulacion-genica', 'Bioquímica - Genética Molecular, Mutaciones y Regulación Génica', 'El tema de Bioquímica - Genética Molecular, Mutaciones y Regulación Génica cubre los mecanismos de herencia, la estructura y función del ADN, la síntesis de proteínas, los tipos de mutaciones y sus consecuencias, así como los procesos de regulación génica en células eucariotas y procariotas. Es fundamental para el examen FIR porque permite comprender cómo los cambios genéticos afectan la farmacología y la respuesta a fármacos, y cómo se regula la expresión génica en contextos clínicos. Disponemos de 11 preguntas oficiales de convocatorias anteriores para que puedas practicar con material real y afianzar tus conocimientos.', 11),
  ('bioquimica-transcripcion-traduccion-y-procesamiento-del-arn', 'Bioquímica - Transcripción, Traducción y Procesamiento del ARN', 'El apartado de Bioquímica - Transcripción, Traducción y Procesamiento del ARN cubre los mecanismos que regulan la síntesis de proteínas, desde la iniciación de la transcripción hasta los pasos de maduración y edición del ARN. Se profundiza en la estructura de los ribosomas, la selección de codones y la modificación post‑transcripcional, aspectos clave para comprender la farmacocinética y la interacción de fármacos con el sistema genético. Disponemos de 11 preguntas oficiales de convocatorias previas, lo que permite practicar con material auténtico y evaluar el dominio de estos procesos.', 11),
  ('farmacocinetica-monitorizacion-farmacocinetica-y-farmacia-clinica', 'Farmacocinética - Monitorización Farmacocinética y Farmacia Clínica', 'El apartado de Farmacocinética - Monitorización Farmacocinética y Farmacia Clínica abarca los principios que rigen la absorción, distribución, metabolismo y excreción de fármacos, así como las técnicas de medición de concentraciones plasmáticas y la interpretación de datos para ajustar dosis. Este tema es esencial porque permite garantizar la eficacia y seguridad de los tratamientos, especialmente en pacientes con variabilidad fisiológica o comorbilidades. Puedes reforzar tu preparación con 11 preguntas reales de convocatorias oficiales anteriores, disponibles para practicar.', 11),
  ('fisiopatologia-renal-y-equilibrio-acido-base', 'Fisiopatología - Renal y Equilibrio Ácido-Base', 'El tema de Fisiopatología - Renal y Equilibrio Ácido-Base cubre los mecanismos de regulación del pH, la función tubular y la interacción con la homeostasis electrolítica, aspectos esenciales para comprender las alteraciones que se evalúan en el examen FIR de Farmacia. Se profundiza en la respuesta renal a desequilibrios ácido-base, la producción y eliminación de ácido, y la influencia de los fármacos en estos procesos, lo que resulta clave para la práctica clínica. Disponemos de 11 preguntas reales de convocatorias oficiales anteriores que puedes usar para entrenar tu dominio de este contenido.', 11),
  ('tecnologia-farmaceutica-disolucion-cinetica-de-degradacion-y-sistemas-de-liberacion-modificada', 'Tecnología Farmacéutica - Disolución, Cinética de Degradación y Sistemas de Liberación Modificada', 'El tema Tecnología Farmacéutica - Disolución, Cinética de Degradación y Sistemas de Liberación Modificada cubre los principios que rigen la solubilidad de los fármacos, la velocidad y mecanismo de sus procesos de degradación, y las estrategias de formulación para controlar la liberación del principio activo. Este contenido es esencial porque permite evaluar la estabilidad, la biodisponibilidad y la eficacia terapéutica de los medicamentos, aspectos clave en la valoración de la calidad farmacéutica. Para afianzar el aprendizaje, disponemos de 11 preguntas reales de convocatorias oficiales anteriores que puedes usar para practicar y medir tu dominio del tema.', 11),
  ('estadistica-y-salud-publica-bioestadistica-descriptiva', 'Estadística y Salud Pública - Bioestadística Descriptiva', 'El tema de Estadística y Salud Pública - Bioestadística Descriptiva cubre las técnicas básicas de análisis de datos, la presentación de resultados mediante medidas de tendencia central, dispersión y distribución, y la interpretación de gráficos y tablas en el contexto de la salud. Es fundamental para el examen porque permite evaluar la capacidad de los candidatos para sintetizar información epidemiológica y tomar decisiones informadas. En la plataforma tienes acceso a 10 preguntas reales de convocatorias oficiales anteriores, ideales para afianzar tus conocimientos.', 10),
  ('estadistica-y-salud-publica-diseno-de-estudios-epidemiologia-y-salud-publica', 'Estadística y Salud Pública - Diseño de Estudios, Epidemiología y Salud Pública', 'El apartado de Estadística y Salud Pública - Diseño de Estudios, Epidemiología y Salud Pública cubre los métodos de recogida y análisis de datos, la planificación de estudios observacionales y experimentales, así como la interpretación de indicadores epidemiológicos y su aplicación en la gestión sanitaria. Este contenido es esencial para el examen FIR, pues permite evaluar la capacidad de diseñar investigaciones que aporten evidencia fiable para la toma de decisiones en el sector farmacéutico y de salud. En la plataforma dispones de 10 preguntas reales de convocatorias oficiales anteriores que puedes usar para afinar tu dominio de estos conceptos.', 10),
  ('farmacologia-aparato-digestivo-y-respiratorio', 'Farmacología - Aparato Digestivo y Respiratorio', 'El apartado de Farmacología - Aparato Digestivo y Respiratorio abarca los fármacos que actúan sobre el sistema gastrointestinal y el sistema respiratorio, incluyendo mecanismos de acción, indicaciones, contraindicaciones y efectos secundarios. Este tema es esencial para el examen FIR, pues evalúa la capacidad de aplicar conocimientos farmacológicos en situaciones clínicas reales. En la plataforma tienes disponibles 10 preguntas oficiales de convocatorias anteriores, lo que te permite practicar con material auténtico y medir tu progreso.', 10),
  ('inmunologia-inmunidad-innata-complemento-y-citocinas', 'Inmunología - Inmunidad innata, complemento y citocinas', 'El apartado de inmunología en el temario FIR cubre la inmunidad innata, el sistema del complemento y la acción de las citocinas, aspectos fundamentales para comprender la respuesta inmunológica y su relación con la farmacología clínica. Se profundiza en los mecanismos de reconocimiento, activación y regulación de la defensa del organismo, así como en la interacción de los fármacos con estos procesos. Además, dispone de 10 preguntas reales de convocatorias oficiales anteriores que permiten practicar y consolidar el conocimiento de manera práctica.', 10),
  ('bioquimica-estructura-de-proteinas-enzimologia-y-senalizacion-celular', 'Bioquímica - Estructura de Proteínas, Enzimología y Señalización Celular', 'El tema “Bioquímica - Estructura de Proteínas, Enzimología y Señalización Celular” cubre la conformación tridimensional de las proteínas, los mecanismos de acción de las enzimas y los principales caminos de señalización intracelular, aspectos esenciales para comprender la farmacología y la fisiopatología de los fármacos. Se incluyen conceptos de plegamiento, dominios funcionales, cinética enzimática y cascadas de señalización que influyen en la eficacia y seguridad de los tratamientos. Además, dispone de nueve preguntas reales de convocatorias oficiales anteriores, lo que permite a los candidatos practicar con material auténtico y afinar su dominio de los contenidos clave.', 9),
  ('fisiopatologia-respiratorio', 'Fisiopatología - Respiratorio', 'El tema de Fisiopatología - Respiratorio cubre los mecanismos patológicos que alteran la función pulmonar, desde la inflamación y la obstrucción de las vías aéreas hasta la alteración de la difusión gaseosa y la respuesta inmunológica. Se centra en enfermedades como el asma, la EPOC y la fibrosis pulmonar, y su impacto en la fisiología respiratoria, lo que resulta esencial para comprender los criterios de diagnóstico y las opciones terapéuticas evaluadas en el examen FIR. Disponemos de 9 preguntas reales de convocatorias oficiales anteriores que puedes usar para practicar y afianzar tus conocimientos.', 9),
  ('inmunologia-inmunopatologia-inmunodeficiencias-autoinmunidad-hipersensibilidad-y-trasplantes', 'Inmunología - Inmunopatología: inmunodeficiencias, autoinmunidad, hipersensibilidad y trasplantes', 'El apartado de Inmunología - Inmunopatología cubre los trastornos del sistema inmunitario, desde inmunodeficiencias primarias y secundarias hasta enfermedades autoinmunes y reacciones de hipersensibilidad, además de los aspectos inmunológicos relevantes en trasplantes. Se profundiza en los mecanismos patológicos, la clasificación de las enfermedades, los criterios diagnósticos y las terapias inmunomoduladoras, aspectos clave para la valoración clínica y la toma de decisiones en el examen FIR. Para afianzar la práctica, dispones de 9 preguntas reales de convocatorias oficiales anteriores que puedes estudiar.', 9),
  ('legislacion-farmaceutica-ensayos-clinicos-farmacovigilancia-y-gestion', 'Legislación Farmacéutica - Ensayos Clínicos, Farmacovigilancia y Gestión', 'El tema “Legislación Farmacéutica - Ensayos Clínicos, Farmacovigilancia y Gestión” cubre los marcos normativos que regulan la investigación clínica, la monitorización de efectos adversos y la administración de medicamentos en la práctica farmacéutica. Se aborda la normativa europea e internacional, los requisitos éticos y la responsabilidad del profesional en la detección y reporte de eventos adversos, así como la gestión de datos clínicos. Este contenido es esencial para el examen FIR, pues evalúa la capacidad de aplicar la legislación en situaciones reales. Disponemos de 9 preguntas oficiales de convocatorias anteriores para que puedas practicar y afianzar tus conocimientos.', 9),
  ('analisis-clinicos-bioquimica-hepatobiliar-y-liquidos-biologicos', 'Análisis Clínicos - Bioquímica Hepatobiliar y Líquidos Biológicos', 'El apartado de Análisis Clínicos - Bioquímica Hepatobiliar y Líquidos Biológicos cubre los estudios de función hepática, bilirrubinas, enzimas, perfil lipídico y análisis de orina, suero y líquido cefalorraquídeo, así como la interpretación de resultados y su relevancia clínica. Este bloque es clave para el examen FIR, ya que exige dominio de los valores de referencia, la identificación de alteraciones patológicas y la correlación con diagnósticos. Disponemos de 8 preguntas oficiales de convocatorias anteriores que puedes usar para afinar tu práctica.', 8),
  ('analisis-clinicos-hemostasia-e-inmunohematologia', 'Análisis Clínicos - Hemostasia e Inmunohematología', 'El apartado de Análisis Clínicos - Hemostasia e Inmunohematología cubre los estudios de coagulación, pruebas de función plaquetaria y los procedimientos de tipificación sanguínea, así como la detección de anticuerpos y la interpretación de resultados en el contexto de la práctica farmacéutica. Este contenido es esencial para el examen FIR, ya que permite a los farmacéuticos garantizar la seguridad y eficacia de los tratamientos que dependen de la correcta valoración de la coagulación y la compatibilidad sanguínea. En la plataforma de FIR Turel dispones de 8 preguntas reales de convocatorias oficiales anteriores para afianzar tus conocimientos.', 8),
  ('analisis-clinicos-marcadores-tumorales-cardiacos-y-oseos', 'Análisis Clínicos - Marcadores Tumorales, Cardiacos y Óseos', 'El apartado de Análisis Clínicos - Marcadores Tumorales, Cardiacos y Óseos cubre la interpretación de pruebas de laboratorio que identifican sustancias específicas asociadas a neoplasias, disfunción cardíaca y procesos óseos, así como su aplicación en la valoración diagnóstica y seguimiento terapéutico. Este contenido es esencial para el examen FIR porque los candidatos deben demostrar dominio de la bioquímica clínica y la capacidad de integrar resultados de laboratorio en la práctica farmacéutica. En la plataforma de FIR Turel dispones de 8 preguntas oficiales de convocatorias anteriores para que puedas ejercitar y afianzar estos conocimientos.', 8),
  ('estadistica-y-salud-publica-estadistica-inferencial-y-modelos', 'Estadística y Salud Pública - Estadística Inferencial y Modelos', 'El apartado de Estadística Inferencial y Modelos dentro de la sección de Estadística y Salud Pública cubre los principios y técnicas para analizar datos de salud, estimar parámetros poblacionales, probar hipótesis y construir modelos predictivos. Este contenido es clave para interpretar estudios epidemiológicos y evaluar intervenciones sanitarias, habilidades que el examen FIR evalúa con frecuencia. En la plataforma tienes acceso a 8 preguntas reales de convocatorias oficiales anteriores, lo que te permite practicar con material auténtico y afinar tu dominio de la materia.', 8),
  ('estadistica-y-salud-publica-pruebas-diagnosticas-y-medidas-epidemiologicas', 'Estadística y Salud Pública - Pruebas Diagnósticas y Medidas Epidemiológicas', 'El tema “Estadística y Salud Pública - Pruebas Diagnósticas y Medidas Epidemiológicas” cubre los principios de análisis estadístico aplicados a la evaluación de pruebas diagnósticas, la interpretación de sensibilidad, especificidad, valores predictivos y la aplicación de medidas epidemiológicas como incidencia, prevalencia y riesgo relativo. Es esencial para el examen, ya que permite valorar la eficacia de los procedimientos clínicos y la toma de decisiones basadas en datos. Disponemos de 8 preguntas reales de convocatorias oficiales anteriores que puedes usar para practicar y afianzar estos conceptos.', 8),
  ('farmacocinetica-diseno-de-regimenes-de-dosificacion-y-estado-estacionario', 'Farmacocinética - Diseño de Regímenes de Dosificación y Estado Estacionario', 'El tema “Farmacocinética - Diseño de Regímenes de Dosificación y Estado Estacionario” cubre los principios que permiten calcular la dosis y la frecuencia de administración para alcanzar y mantener concentraciones terapéuticas estables, considerando parámetros como la vida media, la eliminación y la biodisponibilidad. Se centra en la aplicación práctica de ecuaciones de estado estacionario y en la interpretación de curvas de concentración-tiempo, aspectos esenciales para la planificación de tratamientos seguros y eficaces. Los candidatos pueden reforzar su comprensión con preguntas reales de convocatorias oficiales anteriores, disponibles en la plataforma.', 8),
  ('quimica-farmaceutica-estereoquimica-e-isomeria-de-farmacos', 'Química Farmacéutica - Estereoquímica e Isomería de Fármacos', 'La sección de Química Farmacéutica - Estereoquímica e Isomería de Fármacos cubre la configuración espacial de moléculas, los diferentes tipos de isómeros (geométricos, ópticos y conformacionales) y su impacto en la actividad biológica y la farmacocinética de los medicamentos. Entender cómo la estereoquímica afecta la afinidad a receptores y la metabolización es esencial para responder correctamente a las preguntas de la convocatoria. En la plataforma FIR Turel dispones de 8 preguntas reales de convocatorias oficiales anteriores para afianzar estos conceptos.', 8),
  ('tecnologia-farmaceutica-esterilizacion-formas-parenterales-y-oftalmicas', 'Tecnología Farmacéutica - Esterilización, Formas Parenterales y Oftálmicas', 'El tema “Tecnología Farmacéutica - Esterilización, Formas Parenterales y Oftálmicas” cubre los procesos críticos de purificación y esterilización de productos farmacéuticos, la preparación y control de soluciones parenterales y las especificaciones de formulaciones oftálmicas, aspectos esenciales para garantizar la seguridad y eficacia de los medicamentos. Su relevancia radica en la necesidad de dominar normas de asepsia, técnicas de esterilización y parámetros de calidad que se evalúan en el examen FIR. Disponemos de 8 preguntas oficiales de convocatorias anteriores para que puedas practicar y consolidar tus conocimientos.', 8),
  ('microbiologia-resistencia-bacteriana-y-antibioticos', 'Microbiología - Resistencia bacteriana y antibióticos', 'El tema Microbiología - Resistencia bacteriana y antibióticos cubre los mecanismos de resistencia, la clasificación y uso racional de los antibióticos, así como la interpretación de resultados de sensibilidad. Es esencial para el examen FIR porque permite evaluar la capacidad de diagnosticar y tratar infecciones de forma segura, una competencia clave en farmacia clínica y comunitaria. En la plataforma dispones de 7 preguntas reales de convocatorias oficiales anteriores, ideales para afianzar la práctica y familiarizarte con el estilo de la prueba.', 7),
  ('microbiologia-virologia', 'Microbiología - Virología', 'El apartado de Microbiología - Virología cubre los virus más relevantes para la práctica farmacéutica, sus estructuras, ciclos de vida, mecanismos de infección y las estrategias de prevención y tratamiento, incluyendo vacunas y antivirales. Este contenido es esencial para el examen FIR, pues permite evaluar la capacidad de aplicar conocimientos virológicos en la gestión de medicamentos y la atención al paciente. En la plataforma de FIR Turel dispones de 7 preguntas oficiales de convocatorias anteriores, ideales para afinar tu dominio de la materia.', 7),
  ('tecnologia-farmaceutica-sistemas-dispersos-y-reologia', 'Tecnología Farmacéutica - Sistemas Dispersos y Reología', 'El apartado de Tecnología Farmacéutica - Sistemas Dispersos y Reología aborda los principios que rigen la formación, estabilidad y comportamiento físico de las formulaciones dispersas, desde la selección de excipientes hasta la evaluación de la viscosidad y la tensión de corte. Este conocimiento es esencial para el examen FIR, pues permite diseñar y controlar productos de alta calidad, garantizando su eficacia y seguridad. En la práctica, dispone de 7 preguntas reales de convocatorias oficiales anteriores que facilitan la preparación y la verificación de la comprensión de estos conceptos clave.', 7),
  ('bioquimica-metabolismo-de-aminoacidos-y-ciclo-de-la-urea', 'Bioquímica - Metabolismo de Aminoácidos y Ciclo de la Urea', 'El tema de Bioquímica - Metabolismo de Aminoácidos y Ciclo de la Urea abarca los procesos de degradación y síntesis de aminoácidos, la generación de energía a partir de estos compuestos y la eliminación de amoníaco mediante el ciclo hepático. Este contenido es esencial para el examen FIR, ya que evalúa la comprensión de rutas metabólicas clave y su regulación en el organismo. Además, disponemos de 6 preguntas oficiales reales de convocatorias anteriores para que puedas practicar y consolidar tus conocimientos.', 6),
  ('inmunologia-linfocitos-b-respuesta-humoral-e-inmunidad-de-mucosas', 'Inmunología - Linfocitos B, respuesta humoral e inmunidad de mucosas', 'El apartado de Inmunología - Linfocitos B, respuesta humoral e inmunidad de mucosas cubre la generación y función de los linfocitos B, la producción de anticuerpos y la defensa inmunitaria en superficies mucosas, aspectos clave para comprender la protección contra patógenos y la respuesta a vacunas. Este contenido es esencial para el examen FIR de Farmacia, ya que evalúa la capacidad de aplicar conocimientos sobre mecanismos de defensa y su relación con la farmacología clínica. Disponemos de 6 preguntas oficiales de convocatorias anteriores que permiten practicar y consolidar estos conceptos.', 6),
  ('microbiologia-micologia', 'Microbiología - Micología', 'El apartado de Microbiología - Micología cubre el estudio de los hongos patógenos, sus formas de transmisión, diagnóstico microbiológico y tratamientos antifúngicos, aspectos esenciales para la práctica farmacéutica y la seguridad del paciente. Su relevancia radica en la necesidad de identificar correctamente las infecciones fúngicas y seleccionar la terapia adecuada, tema frecuente en la convocatoria FIR. En la plataforma FIR Turel disponemos de 6 preguntas oficiales reales de convocatorias anteriores, ideales para afianzar el conocimiento y evaluar el dominio de este bloque temático.', 6),
  ('tecnologia-farmaceutica-vias-de-administracion-especiales', 'Tecnología Farmacéutica - Vías de Administración Especiales', 'El tema Tecnología Farmacéutica - Vías de Administración Especiales cubre los principios y técnicas de las rutas no convencionales, como la transdérmica, ocular, nasal, bucal, inhalatoria y subcutánea, además de los dispositivos y formulaciones diseñados para cada una. Su relevancia radica en que el examen exige conocer la farmacocinética, la biodisponibilidad y las indicaciones clínicas de estas vías, pues son fundamentales para la práctica farmacéutica moderna. Para afianzar el aprendizaje, dispones de 6 preguntas reales de convocatorias oficiales anteriores que puedes usar para practicar.', 6),
  ('analisis-clinicos-calidad-analitica-y-fase-preanalitica', 'Análisis Clínicos - Calidad Analítica y Fase Preanalítica', 'El apartado de Análisis Clínicos - Calidad Analítica y Fase Preanalítica cubre los principios que garantizan la exactitud y confiabilidad de los resultados, desde la recolección y manejo de muestras hasta la calibración y control de instrumentos. Se centra en la identificación de fuentes de error, la implementación de protocolos de calidad y la interpretación de datos en el contexto clínico, aspectos esenciales para la toma de decisiones médicas. Los candidatos pueden reforzar su preparación con cinco preguntas reales de convocatorias oficiales anteriores, disponibles para su práctica.', 5),
  ('farmacocinetica-distribucion-volumen-de-distribucion-y-union-a-proteinas', 'Farmacocinética - Distribución (Volumen de Distribución y Unión a Proteínas)', 'El apartado de Farmacocinética - Distribución (Volumen de Distribución y Unión a Proteínas) cubre cómo los fármacos se dispersan en los compartimentos corporales y la influencia de la unión a proteínas plasmáticas en la disponibilidad terapéutica. Este contenido es esencial para comprender la dosificación, la eliminación y la interacción entre medicamentos, factores clave en la práctica farmacéutica. Los candidatos pueden reforzar su aprendizaje con cinco preguntas reales de convocatorias oficiales anteriores, lo que facilita la preparación específica para el examen FIR.', 5);

DO $$
DECLARE
  total_despues int;
  desajustes int;
BEGIN
  SELECT COUNT(*) INTO total_despues FROM public.temas;
  IF total_despues != 66 THEN
    RAISE EXCEPTION 'Se esperaban 66 filas en temas, hay % -- abortando.', total_despues;
  END IF;

  -- LEFT JOIN a proposito: un tema sin fila coincidente en preguntas (p.n_real
  -- IS NULL) es tan grave como un num_preguntas desajustado, y debe abortar
  -- igual -- no solo los casos donde SI hay coincidencia pero el numero falla.
  SELECT COUNT(*) INTO desajustes
  FROM public.temas t
  LEFT JOIN (
    SELECT tema, COUNT(*)::int AS n_real
    FROM public.preguntas
    GROUP BY tema
  ) p ON p.tema = t.tema
  WHERE p.n_real IS NULL OR p.n_real != t.num_preguntas;

  IF desajustes != 0 THEN
    RAISE EXCEPTION '% temas tienen num_preguntas desajustado (o sin coincidencia) respecto a preguntas -- abortando.', desajustes;
  END IF;

  RAISE NOTICE 'OK: % filas en temas, num_preguntas cuadra con preguntas para las % coincidencias.', total_despues, 66;
END $$;

COMMIT;
