-- UPDATE preguntas.explicacion/explicacion_calidad (pase con modelo de vision, Groq)
-- Fuente: ingesta/explicaciones_vision_generadas.json (19 de 20 registros)
-- Excluida id 1039 (omeprazol) a la espera de verificacion manual del punto de
-- protonacion marcado en la imagen -- no se toca en este UPDATE.
-- Modelos: qwen/qwen3.6-27b (mayoria) y qwen/qwen3.8-27b con reasoning_effort=medium
-- para id 1211 (unico caso que requirio el modelo alternativo, ver revision manual).

BEGIN;

DO $$
DECLARE
  pendientes_antes int;
BEGIN
  SELECT COUNT(*) INTO pendientes_antes
    FROM public.preguntas
    WHERE imagen_path IS NOT NULL AND explicacion IS NULL;
  IF pendientes_antes != 20 THEN
    RAISE EXCEPTION 'Se esperaban % preguntas con imagen sin explicacion, hay % -- abortando.', 20, pendientes_antes;
  END IF;
END $$;

UPDATE public.preguntas AS p
SET explicacion = v.explicacion,
    explicacion_calidad = 'vision_ok'
FROM (VALUES
  (767, 'La imagen muestra un proteinograma sérico comparativo donde la fila inferior (paciente) presenta una marcada ausencia de la banda de gammaglobulinas (situada en el polo anódico, +), la cual aparece como una banda ancha y oscura en el control sano de la fila superior. Esta agammaglobulinemia o hipogammaglobulinemia severa es el hallazgo electroforético característico de una inmunodeficiencia, ya que refleja la incapacidad del sistema inmune para sintetizar inmunoglobulinas. Las demás opciones se descartan porque la hipoalbuminemia, aunque podría sugerirse por la menor intensidad de la banda de albúmina, no es el hallazgo principal ni explica la falta de gamma; la inflamación crónica se manifestaría con un aumento policlonal de las gammaglobulinas (banda ancha e intensa) y de las alfa-2 globulinas; y la paraproteinemia o gammapatía monoclonal se identificaría mediante un pico estrecho y denso (pico M) en la región gamma, no por su desaparición.'),
  (1048, 'La imagen muestra la estructura química de la cimetidina, un antagonista de los receptores H2, donde se destaca con un círculo discontinuo el grupo ciano (-CN) unido al nitrógeno del sistema guanidínico. Este fragmento actúa como un potente grupo atrayente de electrones que reduce la densidad electrónica sobre los átomos de nitrógeno de la guanidina, disminuyendo significativamente su basicidad (bajando el pKa desde valores cercanos a 13 hasta aproximadamente 6,8), lo cual es fundamental para minimizar efectos secundarios como la actividad antiandrogénica y evitar una ionización excesiva a pH fisiológico. Las opciones que proponen alterar la duración de acción (B y C) o mejorar directamente la interacción con la diana (A) son incorrectas, dado que el objetivo principal de esta modificación estructural es la modulación de la basicidad para optimizar el perfil de seguridad y eficacia, más que influir directamente en la cinética de eliminación o en la afinidad de unión por sí misma.'),
  (1049, 'La imagen muestra la estructura química del tamoxifeno (A), un modulador selectivo del receptor de estrógeno con un grupo etilo en posición alílica, y su análogo estructural toremifeno (B), donde dicho grupo ha sido sustituido por un grupo clorometilo (marcado con un círculo). Esta modificación se realiza para bloquear la vía metabólica de oxidación del grupo etilo que, en el tamoxifeno, puede generar un intermediario reactivo (catión alílico) capaz de alquilar bases del ADN y causar toxicidad genotóxica, validando así la opción B como la respuesta correcta. Las opciones restantes son incorrectas porque el fármaco original ya posee la lipofilia necesaria para la permeabilidad celular (A), la sustitución no tiene como objetivo principal mejorar la afinidad antagonista sino la seguridad metabólica (C), y no se busca establecer una nueva interacción de unión con el receptor (D) sino evitar la formación de metabolitos reactivos.'),
  (1054, 'La imagen muestra la estructura química de la clorambucil, un análogo de la uracilo sustituido en la posición N1 por dos grupos 2-cloroetilo, lo que la identifica como una mostaza nitrogenada bifuncional. Este compuesto actúa como agente alquilante antineoplásico (opción C) al formar enlaces cruzados en el ADN celular, interrumpiendo la replicación y transcripción del material genético, mecanismo característico de los agentes citotóxicos utilizados en el tratamiento de neoplasias hematológicas como la leucemia linfática crónica. Las opciones A, B y D son incorrectas porque describen mecanismos de acción y clases terapéuticas ajenas a la estructura mostrada: los antivirales análogos de nucleósidos (A) suelen poseer una base nitrogenada modificada y un azúcar, los antifúngicos inhibidores de la timidilato sintasa como la flucitosina (B) son pirimidinas fluoradas sin grupos alquilantes clorados, y los antibacterianos inhibidores de la dihidrofolato reductasa (D) son típicamente derivados de pteridinas como la trimetoprima, no derivados de uracilo con cadenas alquílicas halogenadas.'),
  (1056, 'La imagen muestra la estructura química de la mefloquina, un agente antimalárico, con cinco regiones estructurales marcadas. La acumulación del fármaco en el interior de la vacuola digestiva ácida del parásito Plasmodium se produce mediante el mecanismo de trampa iónica, el cual requiere que la molécula actúe como una base débil capaz de protonarse en un entorno de bajo pH. Los fragmentos b (nitrógeno de la cadena lateral piperidínica) y d (nitrógeno del anillo quinoleínico) son los centros básicos responsables de aceptar un protón, transformando la forma neutra y lipofílica, que difunde a través de la membrana, en una especie catiónica que queda retenida intracelularmente por su incapacidad para atravesar la bicapa lipídica. Las demás opciones son incorrectas porque los grupos hidroxilo (a) y los grupos trifluorometilo (c y e), aunque influyen en la lipofilicidad y la estabilidad electrónica de la molécula, no son los sitios de protonación que generan la carga positiva necesaria para el fenómeno de atrapamiento iónico.'),
  (1164, 'La imagen muestra una estructura lineal de eicosanoide caracterizada por un sistema trieno conjugado adyacente a un anillo epóxido y un grupo éster metílico en el extremo carboxílico, correspondiente a la Leucotriena A4 (LTA4). Esta molécula es el intermedio epóxido inestable formado a partir del ácido araquidónico mediante la vía de la 5-lipoxigenasa y sirve como precursor para las leucotrienas B4, C4, D4 y E4, lo que hace que la opción D sea la correcta. Las opciones de prostaglandinas y prostaciclinas son incorrectas porque estas moléculas poseen un anillo cíclico central (ciclopentano o pirano, respectivamente) que no se observa en esta cadena lineal, mientras que las lipoxinas son derivados hidroxihidroperoxi que carecen del anillo epóxido característico mostrado en la figura.'),
  (1169, 'La imagen muestra la estructura química del lutecio-177 oxodotreotide, destacando el complejo quelato DOTA-Lu (que aporta carga negativa por sus carboxilatos) y la cadena peptídica. La opción A es la correcta porque el radiofármaco posee una carga neta negativa, por lo que se administran aminoácidos básicos como la L-lisina y la L-arginina, los cuales se encuentran protonados y cargados positivamente a pH fisiológico, permitiendo neutralizar la carga electrostática del fármaco y competir por la endocitosis mediada por megalina en el túbulo proximal para reducir la nefrotoxicidad. Las opciones B y D son erróneas al incluir aminoácidos ácidos (aspartato y glutamato) con carga negativa que no neutralizarían la aniónicidad del complejo, y la opción C es incorrecta por proponer aminoácidos neutros que no aportan la carga catiónica necesaria para este mecanismo de protección renal.'),
  (1183, 'La imagen muestra un gel de electroforesis de agarosa con los resultados de un ensayo de PCR-RFLP utilizando la enzima de restricción HhaI, donde la calle 1 corresponde a un marcador de peso molecular y las calles 2, 3 y 4 representan diferentes genotipos del polimorfismo G2478A del gen LEP. Dado que la enzima HhaI reconoce específicamente la secuencia GCGC, la presencia del alelo G mantiene el sitio de corte, resultando en fragmentos de menor tamaño que migran más rápido hacia el ánodo (banda inferior), mientras que la mutación a la adenina (alelo A) destruye el sitio de reconocimiento (ACGC), impidiendo el corte y manteniendo el producto de PCR de mayor tamaño (banda superior). Por tanto, el alelo G se identifica por la presencia de la banda inferior de corte, la cual aparece de forma exclusiva en la calle 4 (homocigoto GG) y en combinación con la banda superior no cortada en la calle 3 (heterocigoto GA), lo que confirma que la opción B es la correcta. Las demás alternativas son incorrectas porque la calle 2 muestra únicamente la banda superior no cortada, correspondiente al genotipo homocigoto para el alelo A (AA), por lo que no contiene el alelo G, descartando así las opciones que incluyen la calle 2 o excluyen la calle 3.'),
  (1196, 'La imagen muestra un cromatograma donde los picos numerados 1 y 3 aparecen superpuestos en una única señal de elución, lo que indica que comparten el mismo tiempo de retención, mientras que los picos 5 y 6 presentan una separación parcial con un valle entre ellos que no alcanza la línea base. Dado que los picos 1 y 3 coeluyen, sus factores de retención son idénticos, lo que implica un factor de selectividad ($\alpha$) igual a 1, y la presencia de una zona de solapamiento entre los picos 5 y 6 sin retorno a la línea base indica que no se ha logrado una separación completa, por lo que su resolución ($R_s$) es inferior al valor de referencia de 1,5 necesario para considerarlos totalmente resueltos, lo que valida la opción A como la única respuesta correcta. Las opciones que sugieren un factor de selectividad superior a 1 para los picos 1 y 3 son erróneas porque ignoran su coelución, y aquellas que afirman una resolución superior a 1,5 para los picos 5 y 6 contradicen la evidencia visual de su solapamiento parcial.'),
  (1198, 'La imagen muestra una curva de titulación espectrofotométrica caracterizada por un aumento lineal de la absorbancia con el volumen de titulador añadido hasta alcanzar un punto de inflexión, tras el cual la señal se estabiliza en una meseta horizontal. Este comportamiento confirma que la opción C es la correcta, ya que indica que el producto de reacción (el complejo Cu-EDTA) es la especie absorbente a la longitud de onda de trabajo; la absorbancia crece proporcionalmente a la concentración de complejo formado a medida que avanza la reacción y se mantiene constante una vez consumido todo el analito, momento en el que la formación del complejo cesa. Las opciones A y B son incorrectas porque, si el analito (Cu2+) fuera el absorbente, la curva presentaría una disminución de la absorbancia a medida que es consumido, mientras que si el titulador (EDTA) absorbiera, la señal permanecería baja hasta el punto final para ascender bruscamente por el exceso de titulador, y la opción D se descarta al no corresponderse con la evolución simple de un solo absorbente (el producto) que domina la señal.'),
  (1201, 'La imagen presenta un esquema instrumental que integra una fuente de luz, un monocromador y un divisor de haces que bifurca la radiación en dos caminos ópticos paralelos, uno destinado a una celda de referencia y el otro a la celda de la muestra, cada uno equipado con su respectivo fotodetector. Esta disposición, que permite la medición simultánea de la intensidad de la luz que atraviesa la referencia y la muestra para calcular la absorbancia y compensar las variaciones de la fuente en tiempo real, corresponde a la configuración típica de un espectrofotómetro de absorción molecular UV visible de haz doble, que es la opción correcta. La alternativa A es inapropiada porque un equipo de haz sencillo mide la referencia y la muestra de forma secuencial sin dividir el haz ni utilizar dos detectores a la vez. Las opciones C y D resultan incorrectas puesto que los espectrofluorímetros detectan la radiación emitida por la muestra a un ángulo de noventa grados respecto a la excitación y no emplean este sistema de comparación simultánea de transmisión a través de celdas de referencia y muestra característico de la espectrofotometría de absorción.'),
  (1211, 'La imagen presenta cinco estructuras orgánicas (A–E) en las que se debe valorar la presencia de quiralidad, y la única que carece de plano de simetría interna es la estructura A, un 2,3‑dibromobutano en el que los dos carbonos asimétricos (C2 y C3, cada uno unido a H, Br, CH3 y al otro carbono estereogénico) adoptan una disposición que no permite superponer la molécula con su imagen especular, es decir, corresponde a uno de los dos enantiómeros (par R,R/S,S) y no al isómero meso, por lo que el compuesto es quiral. En cambio, las demás estructuras poseen un elemento de simetría que las hace aquirales: en B (un trihidroxiglutarato) el carbono central porta dos ramas CH(OH)COOH idénticas y la disposición de los grupos OH genera un plano de simetría (compuesto meso); en C (un butanotriol) el carbono medio lleva dos grupos CH(OH)CH3 equivalentes, anulando la quiralidad; en D (un epóxido diéster) los dos carbonos del anillo de tres miembros son equivalentes por simetría (meso); y en E (un ciclohexanol sustituido por un grupo terc‑butilo en posición 4) el carbono que porta el OH tiene dos trayectos del anillo idénticos por el plano de simetría que pasa por C1 y C4, de modo que no es un centro estereogénico. Por todo ello, la opción que recoge únicamente el compuesto A es la respuesta válida, mientras que B, C, D y E quedan descartadas por ser moléculas meso o simétricas y, por tanto, aquirales.'),
  (1213, 'La imagen ilustra la reacción entre el acetato de etilo (un $\beta$-cetoéster con protones ácidos en posición $\alpha$) y la metil vinil cetona (una cetona $\alpha,\beta$-insaturada) en presencia de etóxido de sodio, resultando en la formación de un anillo de ciclohexenona sustituido. Este proceso se identifica como una anelación de Robinson, una secuencia sintética clásica que consiste en una adición de Michael inicial, donde el enolato del compuesto de metileno activo ataca el carbono $\beta$ de la enona, seguida de una condensación aldólica intramolecular y posterior deshidratación para generar el sistema conjugado cíclico observado. Las demás opciones son incorrectas porque una reacción de Diels-Alder es una cicloadición [4+2] concertada que no implica la formación de enolatos intermedios, una condensación de Claisen describe el acoplamiento de dos ésteres para formar un $\beta$-cetoéster sin la etapa de adición conjugada previa, y una ciclación de Dieckmann es específicamente una condensación de Claisen intramolecular de un diéster, no la secuencia Michael-Aldol mostrada.'),
  (1245, 'La imagen muestra la estructura química del 4-amino-6-cloro-1,3-bencenodisulfonamida (compuesto A) y su producto de ciclización, la hidroclorotiazida, evidenciando la formación de un anillo heterocíclico de siete miembros que incorpora un puente metilénico entre el nitrógeno amino exocíclico y el nitrógeno de la sulfonamida. La opción B es la correcta porque la síntesis de la hidroclorotiazida a partir del precursor A requiere una reacción de condensación con formaldehído, el cual actúa como fuente del grupo metilénico (-CH2-) necesario para cerrar el anillo de bencenotiadiazina mediante un mecanismo de adición nucleófila seguida de deshidratación. Las restantes alternativas son incorrectas dado que el ácido fórmico produciría derivados amídicos en lugar de un puente metilénico, el diclorometano se emplea como disolvente inerte y no participa en la formación de enlaces carbono-nitrógeno, y el fosgeno es un reactivo de inserción de grupos carbonilo o formación de isocianatos, incompatible con la estructura del puente metilénico presente en la molécula objetivo.'),
  (1246, 'La imagen muestra la estructura general de una sulfonamida antibacteriana, caracterizada por un núcleo bencénico sustituido en posición para por un grupo amino ($H_2N-$) y un grupo sulfonamida ($-SO_2-NH-R$). La síntesis adecuada de este derivado 4-aminobenzenosulfonamida se logra mediante la clorosulfonación de la acetanilida, ya que el grupo acetamido es activante y orientador orto/para, dirigiendo la entrada del grupo sulfocloruro preferentemente a la posición para debido a la estereoquímica, a diferencia del grupo amino libre de la anilina que se protona en medio ácido volviéndose desactivante y meta-director; posteriormente, la aminólisis del cloruro de sulfonilo resultante introduce la cadena R y la hidrólisis final elimina el grupo protector acetilo para revelar el amino libre en la posición 4. Las opciones A y D son incorrectas porque la clorosulfonación directa de la anilina o el nitrobenceno conduce predominantemente a isómeros meta debido a la protonación del amino (en anilina) o al carácter desactivante meta-director del grupo nitro, respectivamente, mientras que la opción B falla porque el grupo sulfonamida es meta-director, lo que impediría la obtención del isómero para necesario para la actividad antibacteriana.'),
  (1247, 'La imagen muestra la estructura de un derivado éster de una sal de piridinio, caracterizado por un anillo piridinio catiónico unido a una cadena alquílica hidrofóbica mediante un puente metilénico y un enlace éster. La opción correcta es la B, ya que esta molécula constituye un análogo blando del cloruro de cetilpiridinio, un diseño en el que el enlace éster actúa como un grupo sensible a la hidrólisis enzimática (por esterases), lo que permite que el fármaco ejerza su actividad antimicrobiana y sea posteriormente inactivado rápidamente mediante su escisión metabólica, limitando así su vida media y efectos adversos sistémicos. Las demás opciones son incorrectas porque la hidrólisis de este éster no genera el cloruro de cetilpiridinio activo (que posee una unión directa carbono-nitrógeno), por lo que no es un profármaco; no es un homólogo estructural dado que la diferencia radica en la naturaleza del enlace (éster frente a alcano) y no en la repetición de unidades metilénicas; y el término bioisómero no describe adecuadamente la estrategia de inactivación metabólica controlada que define a este compuesto.'),
  (1248, 'La imagen muestra la estructura química de la fentanilo, un derivado sintético de la piperidina caracterizado por la presencia de un grupo fenetilo en la posición 1 del anillo y un grupo N-fenilpropionamida en la posición 4. Este fármaco es un potente agonista de los receptores opioides mu, lo que le confiere una potente actividad analgésica, por lo que la opción B es la correcta. Debido a su alta lipofilicidad, la fentanilo atraviesa con gran facilidad y rapidez la barrera hematoencefálica, lo que invalida la opción A. Asimismo, no se comporta como antihistamínico H1 ni como antagonista de los receptores dopaminérgicos D1, por lo que las opciones C y D son erróneas al no describir su perfil farmacológico.'),
  (1261, 'La imagen muestra la estructura química del salbutamol (albuterol), un agonista beta-adrenérgico, donde el grupo marcado es un grupo metoxi (-OCH3) en la posición 3 del anillo fenólico. La sustitución del grupo hidroxilo en esta posición por un grupo metoxi impide que la molécula sea sustrato de la catecol-O-metiltransferasa (COMT), enzima que metaboliza rápidamente las catecolaminas como la adrenalina o la isoproterenol, lo que aumenta la vida media del fármaco y permite su administración oral; además, esta modificación estructural, junto con el grupo t-butilo en la amina, confiere selectividad por los receptores beta2 sobre los beta1, aumentando así la relación agonista beta2/beta1, lo que justifica la opción B como la respuesta adecuada. Las opciones A y D son incorrectas porque el fármaco es un agonista selectivo beta2 y el grupo metoxi bloquea, no facilita, el metabolismo por COMT; la opción C es errónea ya que la monoaminooxidasa (MAO) actúa sobre la cadena lateral amina y no sobre el anillo fenólico, por lo que la modificación del anillo no tiene como objetivo principal impedir la desaminación oxidativa.'),
  (1411, 'La imagen muestra la reacción de desprotonación de un alquino terminal (1-butino) por una base genérica A para obtener un anión acetiluro y el ácido conjugado de dicha base. Para que el equilibrio se desplace completamente hacia la derecha, la base empleada debe ser más fuerte que el ion acetiluro generado, lo cual requiere que el pKa de su ácido conjugado sea superior al del alquino (pKa ≈ 25). El amida de sodio (NaNH2) es la opción adecuada porque el ion amida (NH2-) tiene como ácido conjugado al amoníaco (pKa ≈ 38), un valor significativamente mayor que el del sustrato, lo que favorece termodinámicamente la formación del producto. Las demás opciones son incorrectas porque el hidróxido sódico (NaOH) y el etóxido de sodio (EtONa) poseen ácidos conjugados (agua y etanol, con pKa de 15,7 y 16 respectivamente) más ácidos que el alquino, por lo que el equilibrio se mantendría hacia la izquierda, y el agua (H2O) carece de la basicidad necesaria para arrancar el protón ácido del triple enlace.')
) AS v(id, explicacion)
WHERE p.id = v.id;

DO $$
DECLARE
  pendientes_despues int;
  excluida_intacta boolean;
BEGIN
  SELECT COUNT(*) INTO pendientes_despues
    FROM public.preguntas
    WHERE imagen_path IS NOT NULL AND explicacion IS NULL;
  IF pendientes_despues != 1 THEN
    RAISE EXCEPTION 'Se esperaba que solo quedara 1 pendiente (id 1039), quedan % -- abortando.', pendientes_despues;
  END IF;

  SELECT (explicacion IS NULL) INTO excluida_intacta
    FROM public.preguntas WHERE id = 1039;
  IF NOT excluida_intacta THEN
    RAISE EXCEPTION 'La pregunta excluida (id 1039) ya no tiene explicacion NULL -- abortando.';
  END IF;

  RAISE NOTICE 'OK: % preguntas actualizadas con vision_ok, id 1039 intacta.', 19;
END $$;

COMMIT;
